### ISSUE TITLE
Store more than numbers

### ISSUE THREAD

**Issue by carragom** [BenSampo/laravel-enum#1]
Hi I'm checking this package to pair it with my model's enums in Laravel and it looks great. But I was wondering if there was a specific reason to limit the values to numbers. Why not just leave them as strings and allow both?. While normally you would use the pretty `Enum::Key` in your code and store `numeric` value in the database what if that which is stored comes from a legacy system and requires a specific alpha-numeric ugly value?.

For example:

```php
final class LegacyCar extends Enum
{
    const Sedan = 'SE-020';
    const Crossover = 'CR-250';
    const SUV = 'SUV001';
}
```

Would it make sense to remove the numeric constrains?

**Comment by BenSampo** [comment]
For the sake of simplicity and for consistency I'd like to retain the strict typing to just numbers. Of course, feel free to fork this package to fit your use case.

**Comment by BenSampo** [comment]
A recent update has added support for using strings as values.
