### ISSUE TITLE
Value (string) 4 doesn't exist in [0, 1, 2, 3, 4, 5, 6, 7] 

### ISSUE THREAD

**Issue by JustPapi** [BenSampo/laravel-enum#108]
I've created an application with BenSampo/laravel-enum. I use the description of the enum in some blade.php files. However, now I've put the application on a hosting server. And I get this error? 

`<small class="d-inline">Domain:</small><span class="badge badge-soft-dark col ml-3 my-1 d-inline"><?php echo e($task->domain->description); ?><`

Any help much appreciated!

**Comment by atymic** [comment]
Do you have the eloquent casting set up correctly (i.e. if you `dd()` the model, is the value a string on an int?

If not, add it to the casts:

```php
protected $casts = [
	'description' => 'integer',
];
```

**Comment by BenSampo** [comment]
@atymic beat me to it! You're quick!

**Comment by JustPapi** [comment]
@atymic That worked, thank you very much!

**Comment by atymic** [comment]
No worries :)
