### ISSUE TITLE
Attribute casting with flagged enums

### ISSUE THREAD

**Issue by lorlab** [BenSampo/laravel-enum#110]
Hi! Great package!
I have a question: Let's say I have the flagged `UserPermissions` enum from the docs:
```
final class UserPermissions extends FlaggedEnum
{
    const ReadComments      = 1 << 0;
    const WriteComments     = 1 << 1;
    const EditComments      = 1 << 2;
    const DeleteComments    = 1 << 3;
}
```
My `User` model is configured to cast the `permissions` to attribute:
```
protected $enumCasts = [
    'permissions' => UserPermissions::class
];
```
I assign `Read` and `Edit` permissions to my User model like this:
```
$user->permissions = new UserPermissions([UserPermissions::ReadComments,
    UserPermissions::EditComments]);
$user->save();
```
The `permissions` column in the database now has the value `5`, which I guess is correct (101 in binary right?)

But if I now access the `$user->permissions` attribute I get an exception:

`BenSampo/Enum/Exceptions/InvalidEnumMemberException with message 'Value (integer) 5 doesn't exist in [1, 2, 4, 8, 0]`

I was expecting to get an Array with the two Enums, am I doing something wrong? Is this possible to achieve? 
 
I understand you can create shortcuts but in my situation it is not practical to define every possible combination: say for example I have a frontend with checkboxes that allows users to select the combination of values they want.

Thanks!

**Comment by BenSampo** [comment]
Hi @lorlab, the FlaggedEnum functionality is relatively new and I think you've discovered a bug here when using it in combination with the Enum casting.

I haven't had a chance to properly investigate but I suspect the method which tries to cast the value from the DB to an enum needs be updated to include a condition for flagged enums.

I'll try to get to this soon if I can, but if you want to play with this yourself the method in question is `castToEnum` on the `CastsEnums` trait. Pull request appreciated if you get to the bottom of it!

**Comment by BenSampo** [comment]
Hey @lorlab , I've pushed a fix for this. You should update to 1.28.2.

Let me know how it goes.
