### ISSUE TITLE
Use in blade view

### ISSUE THREAD

**Issue by thewebartisan7** [BenSampo/laravel-enum#113]
How I can use this directly in view?
You show example to use for permission, then how can be used with `@can(Permission::ReadPost)` ?

I don't like idea of `@inject()`, maybe you have a better solution.

Thanks

**Comment by TutoDS** [comment]
I use in blade with `App\Enums\CustomerStatus::enable` but when I try without App\Enums appear error.
You know how to use only class name?

**Comment by BenSampo** [comment]
You could look at using an alias. Details in my answer here:
https://github.com/BenSampo/laravel-enum/issues/50#issuecomment-472504251
