### ISSUE TITLE
Add grouped enums which dont appear in toArray etc...

### ISSUE THREAD

**Issue by leeovery** [BenSampo/laravel-enum#115]
Hey,

Just been tinkering over the Xmas period and came across a nice little addition which I believe isn't yet supported. I'd be happy to do a PR but thought I'd open the discussion first to see if its desireable and discuss implementation options.

Best explained in code:

This Enum of used in my app and represents the type of 'point' in the system....

```php
final class PointType extends Enum
{
    public const Earned   = 'earned';
    public const Referred = 'referred';
    public const Spent    = 'spent';
    public const Expired  = 'expired';
    public const Bonus    = 'bonus';
    public const Admin    = 'admin';
}
```

An important distinction for these points are that some are Credit points (they add to the balance) and some are Debit points (they subtract from the balance).

It would be cool if we could add a const with an array of other consts like so:

```php
final class PointType extends Enum
{
    public const Earned   = 'earned';
    public const Referred = 'referred';
    public const Spent    = 'spent';
    public const Expired  = 'expired';
    public const Bonus    = 'bonus';
    public const Admin    = 'admin';

    public const Credit = [
        self::Earned,
        self::Referred,
        self::Bonus,
    ];
    public const Debit  = [
        self::Spent,
        self::Expired,
    ];
}
```

This way I could grab all the credit points like so `PointType::Credit`, and it would obvciously return the array as defined.

The issue is that currently your package isnt set to accept arrays as values of enums. This is correct behaviour but also this above funcitonality would be cool. 

Im thinking that perhaps theres a way of defining extra consts like above, but excluding them from the `getConstants` method etc. These additional grouped enums would be simply used as literal groupings of enums.

What are your thoughts?

**Comment by BenSampo** [comment]
Hey @leeovery

While good for your use case, I think it's pretty bespoke and I don't think makes sense to implement as a feature on this package.

You've probably already solved this another way given the amount of time that has passed, but you might be able to accomplish something similar using [flagged enums](https://github.com/BenSampo/laravel-enum#flaggedbitwise-enum).

```
final class PointType extends FlaggedEnum
{
    const Earned      = 1 << 0;
    const Referred     = 1 << 1;
    const Spent      = 1 << 2;
    const Expired      = 1 << 3;
    //...
    
    // Shortcuts
    const Credit = self::Earned | self::Referred;
    const Debit = self::Spent | self::Expired;
}
```
