### ISSUE TITLE
Can support Lumen?

### ISSUE THREAD

**Issue by lifeblood** [BenSampo/laravel-enum#118]
UP

**Comment by atymic** [comment]
Looking at the deps, I think you should be able to use it on lumen with eloquent. Have you tried? If not, you should have a go and report back if there's issues.

**Comment by lifeblood** [comment]
ok
have .NET enum description function ?
https://www.codementor.io/@cerkit/giving-an-enum-a-string-value-using-the-description-attribute-6b4fwdle0

**Comment by atymic** [comment]
Yes, you should check the docs:
https://github.com/BenSampo/laravel-enum#localization
