### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by chapeupreto** [BenSampo/laravel-enum#12]
Considering `UserType` sample class, there are 3 failing tests:

> on `testEnumGetKey()`:

```php
$this->assertEquals('StringTest', UserType::getKey('TEST'));
```

> on `testEnumGetValue()`:
```php
$this->assertEquals('TEST', UserType::getValue('StringTest'));
```

> on `testEnumGetDescription()`:
```php
$this->assertEquals('StringTest', UserType::getDescription('TEST'));
```

Such failings are because of scalar type declaration used by those methods.

Furthermore, because `switch/case` does _loose comparison_ (for example ,`TEST == 0` evaluates to `true`) , it's better to change `Enum.stub` file as well.

**Comment by BenSampo** [comment]
Thanks you @chapeupreto! Merged your PR to fix this.
