### ISSUE TITLE
AbstractAnnotationCommand fails with PREG_JIT_STACKLIMIT_ERROR on large existing docblocks

### ISSUE THREAD

**Issue by mortenscheel** [BenSampo/laravel-enum#120]
The `preg_replace()` call to remove the existing docblock returns null if the model has a large, existing docblock (more than approximately 50 lines on my machine).
`preg_last_error()` returns 6 (`PREG_JIT_STACKLIMIT_ERROR `).

Having large existing docblocks is not that uncommon when using `barryvdh/laravel-ide-helper` to write docblock annotations for properties and methods.

I managed to fix the issue by simplifying the regex to `#(\n?\/\*\*.*)[\n]?%s#ms`, but I don't know if this works in all possible use cases.

Setting `pcre.jit=0` in php.ini also fixes the issue.

Tested on Windows with PHP 7.3 and 7.1

**Comment by BenSampo** [comment]
Can you submit a PR for this?

**Comment by atymic** [comment]
See #157
