### ISSUE TITLE
Pipe syntax enum rule is not registered?

### ISSUE THREAD

**Issue by brizzo** [BenSampo/laravel-enum#127]
When validating request data using the `enum` rule with pipe syntax I get a `Validator::validateEnum does not exist` exception. For example:

```
'status' => 'required|enum' . Status::class
```

I'm using version 1.32. Looking at the `EnumServiceProvider` it looks like the `enum` rule is not being registered in the `bootValidators` function. The Validator is extended for the `enum_key` and `emum_value` rules, but `enum` is missing.

**Comment by BenSampo** [comment]
Yep you're right, it's missing. Fancy having a go a PR for that @brizzo?

**Comment by atymic** [comment]
@brizzo looking at your example, it looks like you want the `enum_value` validator. You're trying to check that `status` is one of the enum values right?

@BenSampo not sure what the `enum` validator would do?

**Comment by Daniyal-Javani** [comment]
Hi @BenSampo
I'm interested in contribution, can you tell me what json should I have in the request to pass the following validation?
https://github.com/BenSampo/laravel-enum/blob/d0604ab47f48b0003ed2f769e0009231f694fabc/src/Rules/Enum.php#L41-L44
and you mentioned here:

> #### Enum instance

> Additionally you can validate that a parameter is an instance of a given enum.

```php
use BenSampo\Enum\Rules\Enum;

public function store(Request $request)
{
    $this->validate($request, [
        'user_type' => ['required', new Enum(UserType::class)],
    ]);
}
```

Here is my commit with some assumptions! https://github.com/Daniyal-Javani/laravel-enum/commit/d0604ab47f48b0003ed2f769e0009231f694fabc

**Comment by BenSampo** [comment]
@Daniyal-Javani This is for when you have cast a parameter to an enum before validation e.g. in a FormRequest class.

Your commit looks good, but can you back it up with a test in https://github.com/BenSampo/laravel-enum/blob/master/tests/EnumPipeValidationTest.php?

Thanks for your work so far!

**Comment by Daniyal-Javani** [comment]
Thanks for your attention @BenSampo 
Sure, I will work on it.
