### ISSUE TITLE
Non-semantic version tags break tooling assumptions

### ISSUE THREAD

**Issue by spawnia** [BenSampo/laravel-enum#135]
The recent releases, such as https://github.com/BenSampo/laravel-enum/releases/tag/v1.36, have been tagged with a version number that does not follow the default semantic version format `x.y.z`.

This breaks some tooling that deals with dependencies. For example, my IDE usually shows me the latest versions when editing `composer.json`. Now, it defaults to the latest proper semantic version, placing the actual newest version somewhere down the list.

![image](https://user-images.githubusercontent.com/12158000/77410654-82439300-6dbb-11ea-8f0a-384855391886.png)

Please consider sticking to conventional semantic version tags in the future. Thanks for your hard work on this package, i much appreciate it.

**Comment by BenSampo** [comment]
Acknowledged, thanks.
