### ISSUE TITLE
Using flagged enums with eloquent

### ISSUE THREAD

**Issue by wbaryla** [BenSampo/laravel-enum#140]
Hello, I can't figure out how could I select records based on flagged enums (for example something like User::whereHasUserPermission(UserPermission::CAN_EDIT)). Does anyone know how to do it?

**Comment by BenSampo** [comment]
This is untested, but you should be able to do something like this where `permission` is the name of your column in the DB table.

```php
User::whereRaw('(permission & ?) != 0', [UserPermission::CAN_EDIT]);
```

This also may help understand what's going on here:
https://stackoverflow.com/questions/143712/comparing-two-bitmasks-in-sql-to-see-if-any-of-the-bits-match

It might be useful to extract this into a macro on Eloquent so you could do something like this instead:

```php
User::whereHasFlag(UserPermission::CAN_EDIT);
```

Anyway, let me know how this goes.

**Comment by wbaryla** [comment]
Thank you for the quick reply! Your solution works like a charm!
