### ISSUE TITLE
Map Enums to Enums

### ISSUE THREAD

**Issue by madsem** [BenSampo/laravel-enum#146]
Hey Ben,

great package, thanks for that.

I'm having a case where I'm integrating multiple third-party API's and need to map several of their returned fields to a common ENUM value in my application.

Example:
```php
// Their SDK (Api1)
const Paused = 'Paused';

// Their SDK (Api2)
const Paused = 'inactive';
```

My application:
```php
const Paused = 2;
```

Now, because different API's return different values for the same type of field, I need to map them all to a common value used in my application, and also be able to revert to the original value.

PHP doesn't allow me to do this:
```php
const Api1Status::Paused = MyApp::Paused;
```

So using an array map would be the only way, so that I can use the Enum classes of the Api's SDK's.
```php
// Api1Status.php
const MAP = [
  Api1Status::Paused => MyApp::Paused,
];

// Api2Status.php
const MAP = [
  Api2Status::Paused => MyApp::Paused,
];
```

The only other way would be to hardcode the external API keys, but then I wouldn't be able to use the SDK Enum classes, and if anything ever changes things would start breaking.

Is this somehow doable with you package, or something worth integrating?

Thanks!

**Comment by BenSampo** [comment]
I'm sure you found a solution to this in the end given that it was a few months ago.

For the sake a posterity this feels like an implementation problem rather than anything the package can solve.
