### ISSUE TITLE
Laravel 5.5 (php 7.1) instalation issue

### ISSUE THREAD

**Issue by danielpolifabro** [BenSampo/laravel-enum#149]
I couldnt install the package on Laravel 5.5 because the dependency "hanneskod/classtools" needs PHP 7.2

![Image](https://user-images.githubusercontent.com/49653877/85569120-a5731e00-b608-11ea-84f4-93288af68f11.JPG)

**Comment by atymic** [comment]
PHP 7.1 is well out of support:
https://www.php.net/supported-versions.php

That being said, what are your thoughts on this @BenSampo?
