### ISSUE TITLE
Adding hasFlag for elequent query builder

### ISSUE THREAD

**Issue by abilogos** [BenSampo/laravel-enum#155]
Hi,
i think one important feature for flagged enums would to query DB using query builder and enums.

    Order::where("client_id",Auth::id())
                   ->whereRaw("order_status"." & ?",[OrderStatus::Ready()])
                   ->get();
its what i was done.

but could have a nicer method like:

        ->whereHasFlag("order_status",OrderStatus::Ready())

it would be my pleasure to contribute and make a PR.
but i dont know where to start, to modify query builder?

**Comment by BenSampo** [comment]
Yes I like this idea.

You'll want to create a trait which can be used on a model which adds query scopes.

https://laravel.com/docs/7.x/eloquent#local-scopes

**Comment by abilogos** [comment]
Thanks Ben.
I will make it work.

Thanks about The Guide.
