### ISSUE TITLE
Remove model annotation command.

### ISSUE THREAD

**Issue by atymic** [BenSampo/laravel-enum#157]
In Laravel 7 with custom casts, PHP IDE helper is able to correctly generate hints for the enum casts. Maybe we can remove the model annotation and point people there?

The command is actually currently broken anyway since I forgot to update in the `2.0` PR (it's looking for the trait, and early returns since it doesn't exist).

**Comment by BenSampo** [comment]
Sounds good, let's get rid. Do you want to PR @atymic?

**Comment by atymic** [comment]
PR'd 👍
