### ISSUE TITLE
Problem with using two enum classes

### ISSUE THREAD

**Issue by KingErfan** [BenSampo/laravel-enum#160]
hello,
I have a problem with using two Enum classes.
look here : 
![Screenshot (3)](https://user-images.githubusercontent.com/13975671/89304546-cce6ed00-d682-11ea-881e-32609af26123.png)
now I have defined my values in both like here 
namespace App\Enums;

use BenSampo\Enum\Enum;

/**
 * @method static static FROM0TO10()
 * @method static static FROM10TO50()
 * @method static static FROM50TO100()
 * @method static static FROM100TO500()
 * @method static static FROM500TO1000()
 * @method static static FROM1000TO10000()
 * @method static static MORETHAN10000()
 */
final class CompanySize extends Enum
{
    const FROM0TO10 = 0;
    const FROM10TO50 = 1;
    const FROM50TO100 = 2;
    const FROM100TO500 = 3;
    const FROM500TO1000 = 4;
    const FROM1000TO10000 = 5;
    const MORETHAN10000 = 6;
}

and the DegreeLevel like this : 
namespace App\Enums;

use BenSampo\Enum\Enum;

/**
 * @method static static DIPLOMA()
 * @method static static BACHELOR()
 * @method static static MASTER()
 * @method static static PHD()
 */
final class DegreeLevel extends Enum
{
    const DIPLOMA = 10;
    const BACHELOR = 11;
    const MASTER = 13;
    const PHD = 14;
}

now when I want to load one const from DegreeLevel I get consts from CompanySize
and even inside the packages code 
in getKey() in static::getConstants() when i dump calledClass it gives me the CompanySize even I call getKey on DegreeLevel
would you please help me why is this happening?

**Comment by atymic** [comment]
Can you post your calling code?

**Comment by KingErfan** [comment]
I Solved It
the problem was that the value of the enum that I gave to getKey() method 
was the number but as a string (it was '10' not 10)
then the class can't find the related key
thanks
