### ISSUE TITLE
enum cast getChanges() not work as expect?

### ISSUE THREAD

**Issue by miaoyaoyao** [BenSampo/laravel-enum#166]
![image](https://user-images.githubusercontent.com/3992080/91697566-ed339a00-eba3-11ea-80c7-ecc18aea4115.png)
The column status in mysql not change, but getChanges() return the column change?

**Comment by BenSampo** [comment]
This is a Laravel core issue, so I suggest you raise an issue there instead. It's not a package issue or anything I can solve through this package.

**Comment by miaoyaoyao** [comment]
Thank you very much, I'll close this issue.

**Comment by MrJmpl3** [comment]
> 
> 
> This is a Laravel core issue, so I suggest you raise an issue there instead. It's not a package issue or anything I can solve through this package.

I think, the problem is in "originalIsEquivalent", the package send a object with "value", "key" and "description", when to the comparation only need a value result.

**Comment by MrJmpl3** [comment]
@BenSampo In words of Taylor: "The set method should return an array of raw key / values that are primitive types that can be directly stored in the database."

I think in this package, the set method return a instance of class Enum based in the value.

https://github.com/laravel/framework/pull/34775

**Comment by atymic** [comment]
PR open here 👍 
https://github.com/BenSampo/laravel-enum/pull/187

**Comment by MrJmpl3** [comment]
Oh, that was fast. 😃
