### ISSUE TITLE
Laravel 7.26.1 and laravel-enum 2.2

### ISSUE THREAD

**Issue by makroxyz** [BenSampo/laravel-enum#167]
Native cast doesn't work anymore, works if downgraded to 2.1

**Comment by BenSampo** [comment]
Can you provide more details and/or an example?

**Comment by makroxyz** [comment]
this is my enum
```php
use BenSampo\Enum\Contracts\LocalizedEnum;
use BenSampo\Enum\Enum;

final class ProductSellType extends Enum implements LocalizedEnum
{
    const FEE = 'fee';
    const SELLING = 'selling';
}
```

this is model:
```php
class MyMode extends \Illuminate\Database\Eloquent\Model
{
    protected $casts = [
        'sell_type' => ProductSellType::class,
   ];
}
```

Simply sell_type attribute is simple string with version 2.2, while it was a ProductSellType object  in 2.1

**Comment by BenSampo** [comment]
How are you accessing the `sell_type` prop?

**Comment by makroxyz** [comment]
```php
MyModel::first()->toArray()
```

but all my tests with assertJson now fail

**Comment by BenSampo** [comment]
This is expected behaviour. If you're casting the model to an array (or to JSON) all enum instances will become the enum value.

You can override this if you want to by overriding the `toArray` method on the base Enum class.

Alternatively, access the attribute directly to access the enum instance e.g. `$model->sell_type` will be an instance of `ProductSellType`

**Comment by makroxyz** [comment]
Using new MyModelResource(MyModel) in the toArray method I'm using $this->sell_type... but it's a string!
with 2.1 everything was fine!

So was the 2.1 wrong??

**Comment by BenSampo** [comment]
Yes 2.1 was wrong.

You could try one of the following solutions if you need to:

1)

```php
final class ProductSellType extends Enum implements LocalizedEnum
{
    const FEE = 'fee';
    const SELLING = 'selling';

    public function toArray()
    {
        return $this;
    }
}
```

2)

```php
class MyModel extends \Illuminate\Database\Eloquent\Model
{
    protected $casts = [
        'sell_type' => ProductSellType::class,
   ];

   public function toArray()
   {
       return [
           'sell_type' => [
               'key' => $this->sell_type->key,
               'value' => $this->sell_type->value,
               'description' => $this->sell_type->description,
           ],
           // ... other attributes
       ];
   }
}
```

**Comment by uguurozkan** [comment]
I believe v2.1.0 has more capabilities. For example, in our project we return additional fields like `group` along with `key`, `value`, and `description`. We use `group` to group enum instances in a dropdown, `description` to show user the translation and `value` as the database value. Then when we want to send only the value, we send it in a resource. 

The solution (1) you gave above solves the problem, but putting it in the `README.md` file may benefit other people, too.

```
{
    "success": true,
    "data": [
        {
            "name": "FREELANCER_EMPLOYEE",
            "value": "freelancer_employee",
            "description": "ASSOCIATE_TYPE.FREELANCER_EMPLOYEE",
            "group": "employee",
            "translation": "Freelancer Çalışan"
        },
        {
            "name": "FULL_TIME_EMPLOYEE",
            "value": "full_time_employee",
            "description": "ASSOCIATE_TYPE.FULL_TIME_EMPLOYEE",
            "group": "employee",
            "translation": "Tam Zamanlı Çalışan"
        },
        {
            "name": "CUSTOMER",
            "value": "customer",
            "description": "ASSOCIATE_TYPE.CUSTOMER",
            "group": "trader",
            "translation": "Müşteri"
        }
    ],
    "message": "ASSOCIATE_TYPE.INDEX.SUCCESS"
}
```
