### ISSUE TITLE
Breaking changes in minor version

### ISSUE THREAD

**Issue by jameswilddev** [BenSampo/laravel-enum#170]
Hello!  Long-time package user here.

The upgrade from 2.1.0 to 2.2.0 included a commit (https://github.com/BenSampo/laravel-enum/commit/ee0a511d5c6b562653ceaef4ce06515dc96a7aab) which introduced breaking changes:

- Serialization to JSON changed from being an object containing the different forms of the instance to being only the value string.
- `toSelectArray` became `asSelectArray`.

Neither of these changes are wrong per se, but they were breaking and should only have been made with a major version number increment - we were fortunate to have caught these early (and have updated our codebases to match).

Thank you for this wonderful package, look forward to using it on lots more projects in future!

**Comment by BenSampo** [comment]
Noted, thanks for the feedback @jameswilddev.

Apologies if this caused you any bother.

**Comment by bolechen** [comment]
also break my project, :'(

**Comment by atymic** [comment]
Shouldn't we at least leave the old `toSelectArray`? There's no real need to remove it in a minor version, just mark it as deprecated and remove in the next major version.

**Comment by MartinP7r** [comment]
> Serialization to JSON changed from being an object containing the different forms of the instance to being only the value string.

Is there any way to get the old behavior for JSON serialization, i.e. and object like the following?

```json
array(
     'value' => 1,
     'key' => 'a',
     'description' => 'some',
  )
```

I'm passing arrays of enums to javascript and have been using the `value`,`key`,`description` keys.   
My only other choice is probably to map the array of enums the way I want it myself.

**Comment by atymic** [comment]
See here @MartinP7r 
https://github.com/BenSampo/laravel-enum/pull/184

**Comment by MartinP7r** [comment]
Thanks so much @atymic !
