### ISSUE TITLE
Need default value

### ISSUE THREAD

**Issue by uguurozkan** [BenSampo/laravel-enum#171]
When we get value from database and if it is null, it cannot be casted. Therefore, we cannot use methods like `is`, `in`, etc.

I believe if we add a private default value, we can overcome this problem. For example, when we tried to cast a null value from database, instantiate it with default value. By doing this there will always be an enum object, even if it is a null enum, we can use its methods.

Also if we make it public people can use it, too. Although, I'm not sure if it's a good idea.

What are your thoughts?

**Comment by BenSampo** [comment]
Hi @uguurozkan, take a look at the `parseDatabase` method: https://github.com/BenSampo/laravel-enum#casting-underlying-native-types

You should be able to use this to return a default enum value for null e.g

```php
final class UserType extends Enum
{
    const Administrator = 0;
    const Moderator = 1;
    const Member = 2;
    
    public static function parseDatabase($value)
    {
        if ($value === null) {
            return UserType::Member;
        }

        return $value;
    }
}
```

In this case, any user rows which have a null value for their user type will be set to Member.

**Comment by uguurozkan** [comment]
This is a good solution and can resolve most of the problems, but what I wanted to say is that we don't want to set them to an actual value. Because this can cause some other problems. e.g

```php
if ($commercialDoc->commercial_doc_type->in([CommercialDocType::SALE_INVOICE, CommercialDocType::PURCHASE_INVOICE]) {
    throw new NotTransformableException();
}
```

Here! `commercial_doc_type` can be null. But if I set it to an existing value, the check may be wrong. In order to prevent this, I have to create an empty value (e.g `null`) for each enum class. In my case I can create one in my base class, but my point is this can be pull up to package's enum class so that people do not need to create an intermediary class to do that.

**Comment by atymic** [comment]
This will be solved in PHP8 via nullsafe operator 👍

**Comment by uguurozkan** [comment]
@BenSampo Your solution didn't work. Still got null.

@atymic That will be cool. I'm waiting it, too. But until it is ready, we can do something about this issue, I think. Therefore; I created a PR.
