### ISSUE TITLE
Flagged enum is not being cast when parsed from the DB.

### ISSUE THREAD

**Issue by goddas** [BenSampo/laravel-enum#173]
Not sure if this is a bug, or I'm just doing something wrong. I'm on version 2.1. Please take a look and advise:

//Enum class:
```
final class Subject extends FlaggedEnum
{
    const Yoga =   1 << 0;
    const Dance =   1 << 1;
    const Fitness = 1 << 2;
}
```
I have a form which submits an array of values, when I save the model using casts (lets say Yoga and Fitness), the database field has a value of 5, which seems correct because it is 101 in binary. So the cast works fine when saving the model.

//Model
```
class Instructor extends Model
{
     protected $casts = [
         'subjects_taught' => Subject::class,
     ]
}
```

The problem is the cast does not work when getting the attribute
```
dd($user->instructor->subjects_taught);

App\Enums\Subject {#1689 ▼
  +value: 5
  +key: null
  +description: null
}
```
I expect to get an array here with Yoga and Fitness enums.

**Comment by BenSampo** [comment]
Hi @goddas - take a look at the [`getFlags()`](https://github.com/BenSampo/laravel-enum#getflags-enum) method.

```php
dd($user->instructor->subjects_taught->getFlags());
```

**Comment by goddas** [comment]
`getFlags()` works! It is probably worth adding this bit to the docs, as it seems quite unintuitive to have to call a method there. 
Otherwise thanks for the package! It has been really useful so far.
