### ISSUE TITLE
EnumIn Validation Rule

### ISSUE THREAD

**Issue by uguurozkan** [BenSampo/laravel-enum#174]
Similar to [Laravel's `in` rule](https://laravel.com/docs/7.x/validation#rule-in) we often need it for enum classes.

Can we add this rule?

**Comment by atymic** [comment]
Use the `EnumValue` rule :)
https://github.com/BenSampo/laravel-enum/blob/master/src/Rules/EnumValue.php

**Comment by uguurozkan** [comment]
I know that rule @atymic.  I contributed it in https://github.com/BenSampo/laravel-enum/pull/27. :)

But it only checks whether the attribute is a valid enum. What I want is subset of it. For example; the attribute can only be `admin` or `moderator`, and it cannot be `guest`:
```php
'user_type_rule_value'  => ['bail', 'required', 'enum_value:' . UserType::class],
'user_type_rule_in      => ['bail', 'required', 'enum_in:' . UserType::Administrator . ',' . UserType::Moderator] // Or some other clever way.
```
or
``` php
use BenSampo\Enum\Rules\EnumKey;

public function store(Request $request)
{
    // Enum Value
    $this->validate($request, [
        'user_type_rule_value' => ['required', new EnumValue(UserType::class)],
    ]);
     
    // Enum In
    $this->validate($request, [
        'user_type_rule_in' => ['required', new EnumIn([UserType::Administrator, UserType::Moderator])],
    ]);
}

Right now we use Laravel's `Rule:in` method, but I believe we can incorporate `Enum:in()` method with a rule. 

Thoughts?

**Comment by atymic** [comment]
Oh, I see.
I don't really see the point to be honest, I guess the only advantage is it could protect you from putting non emum values in there? Otherwise, it's the exact same to write, minus two chars?

**Comment by mikkoaf** [comment]
In a similar use case I have thought of using a separate enum which handles the subset. This subset enum can be coerced by values to the parent enums and vice versa. In some use cases the subset of the enum value could also be checked by having an array or collection of the original enum's values.

The subset of the enum benefit of protecting from non-enum values.

```
use UserType;

class AdministrativeUserType extends Enum
{
    public const Administrator = UserType::Administrator;

    public const Moderator = UserType::Moderator;
}
```

```
use BenSampo\Enum\Rules\EnumKey;

public function store(Request $request)
{
    // Enum Value
    $this->validate($request, [
        'user_type_rule_value' => ['required', new EnumValue(UserType::class)],
    ]);
     
    // Enum In
    $this->validate($request, [
        'user_type_rule_in' => ['required', new EnumValue(AdministrativeUserType::class)],
    ]);
}
```
