### ISSUE TITLE
Cache Enum value instances to allow strict comparison

### ISSUE THREAD

**Issue by hackel** [BenSampo/laravel-enum#178]
Several other PHP Enum libraries implement the [multiton pattern](https://en.wikipedia.org/wiki/Multiton_pattern) so that only a single instance of a particular Enum value is ever returned, thereby allowing strict comparisons.  Is this a feature you would be interested in adding to this library?  

```php
$admin = UserType::fromValue(UserType::Administrator);
// Instead of:
$admin->is(UserType::Administrator()); // true
// One could also check equality directly:
$admin === UserType::Administrator(); // true
```

The implementation would be quite simple, and could even use WeakReferences if the requirements were increased to PHP 7.4.

(See https://github.com/Elao/PhpEnums#compare for an example.)

**Comment by BenSampo** [comment]
Seems like a good idea to me @hackel, nice suggestion. Do you want to submit a PR?

**Comment by BenSampo** [comment]
Given that Enums will be a core part of PHP soon, this probably isn't worth implementing any more.
