### ISSUE TITLE
[v2.2.0] Issue with laminas/laminas-eventmanager dependency version using v3.3.0 instead of v2.x

### ISSUE THREAD

**Issue by fylzero** [BenSampo/laravel-enum#181]
I have a project on Laravel 7, not quite ready for Laravel 8 upgrade just yet.

After running composer update I am being told I need PHP v7.3+ because the dependency of this enum package.

This file:
vendor/laminas/laminas-code/composer.json

This line:
"laminas/laminas-eventmanager": "^2.6 || ^3.0",

...is causing the event manager package to use v3.3.0 by default, which requires PHP v7.3 and I am currently stuck on v7.2.5 until my company performs a server upgrade.

Not sure why this is happening.

To reproduce:

- Spin up a fresh copy of Laravel 7
- Install bensampo@2.2.0
- Run composer update
- Run composer show laminas/laminas-eventmanager

Result:
name : laminas/laminas-eventmanager
versions : * 3.3.0
requires : php ^7.3 || ^8.0

**Comment by atymic** [comment]
Can you post the output of `composer why laminas/laminas-eventmanager` please?

**Comment by fylzero** [comment]
@atymic
laminas/laminas-code          3.4.1  requires  laminas/laminas-eventmanager (^2.6 || ^3.0)
laminas/laminas-eventmanager  3.3.0  replaces  zendframework/zend-eventmanager (^3.2.1)
