### ISSUE TITLE
Enum to array

### ISSUE THREAD

**Issue by akos-vomo** [BenSampo/laravel-enum#19]
Hi,

it would be nice if there would be on option for getting all the possible enum values as an array. Either by making the ``getConstants()`` function public, or by creating an accessor in the Enum class:
```
public static function toArray()
    {
        return self::getConstants();
    }
```

What do you think?

**Comment by BenSampo** [comment]
You can use the [`getValues()`](https://github.com/BenSampo/laravel-enum#getvalues-array) function to get an array of all the values.

Is that what you're after?

**Comment by akos-vomo** [comment]
No, I'm talking about an associative array where the keys are the defined constant names, and the values are the constant values. 
Simple example:
```
final class UserGender extends Enum
{
    const Female = 'F';
    const Male = 'M';
}
```
and then calling ``UserGender::toArray()`` would return 
```
[
  'Female' => 'F',
  'Male' => 'M'
]
```

It's the exact same functionality you implemented in the ``Enum::getConstants()`` method. But that method is not public. That's why I wrote it should be either public, or there should be a public accessor method like e.g. ``Enum::toArray()``.

(Btw, of course I could do something like this in the current status, but it's ugly and ineffective: )
```
array_combine(Enum::getKeys(),Enum::getValues())
```

**Comment by BenSampo** [comment]
Thanks for clarifying @akos-vomo, I do see what you mean now. I'll add this in.

**Comment by akos-vomo** [comment]
:+1: Thank you @BenSampo . Feel free to close this issue after.

**Comment by BenSampo** [comment]
Fixed

https://github.com/BenSampo/laravel-enum/commit/42a3a978952ff90bb15ecdf0f042f537a418590d
