### ISSUE TITLE
How translate enum array?

### ISSUE THREAD

**Issue by piterssson** [BenSampo/laravel-enum#191]
Hello,
I have enums with arrays for example:

`const one = ['id' => 1, 'title' => 'example'];`

How translate title inside variable enum ?

**Comment by BenSampo** [comment]
Can you share your enum definition?

**Comment by piterssson** [comment]
> Can you share your enum definition?

`<?php

namespace App\Enums;

use BenSampo\Enum\Enum;
use Illuminate\Contracts\View\Factory;

final class Subscriber extends Enum
{
    const one = ['id' => 1, 'title' => 'example', 'extended' => 0];
    const two = ['id' => 2, 'title' => 'example 2', 'extended' => 1];
}
`
and in controller I get elements:

`collect(Subscriber::toArray())`

**Comment by BenSampo** [comment]
Array values aren't really supported by this library, I'm surprised that works at all. I'm not really sure what you're trying to achieve by doing this either.
