### ISSUE TITLE
[v2.2.0] $enumCasts not working

### ISSUE THREAD

**Issue by raditzfarhan** [BenSampo/laravel-enum#192]
- Package Version: v2.2.0
- Lumen Version: 7.2.2
- PHP Version: 7.4.6

### Description:
After upgraded from v2.1.0 to v2.2.0, the `$enumCasts` no longer working.

This is the code on model.
```
public $enumCasts = ['status' => ActiveStatus::class];
```

Before upgrade:
![image](https://user-images.githubusercontent.com/1203676/98232801-13f1c080-1f99-11eb-867b-d3f9ba155b82.png)

After upgrade:
![image](https://user-images.githubusercontent.com/1203676/98232910-384d9d00-1f99-11eb-84d5-b7e35d0922ab.png)

### Steps To Reproduce:
1. Use `$enumCasts` in your model.
2. Upgrade from v2.1.0 to v2.2.0.

**Comment by BenSampo** [comment]
See https://github.com/BenSampo/laravel-enum#customising-model-toarray-behaviour
