### ISSUE TITLE
VSCode does not understand the is() parameter 

### ISSUE THREAD

**Issue by ihorhnatchuk** [BenSampo/laravel-enum#193]
I'm using IDE VS code and it doesn't understand the methods from your package is (), in (). https://prnt.sc/vhdk5b

**Comment by BenSampo** [comment]
VS Code doesn't know that the `type` property on your `tournament` model is an Enum.

Take a look at https://github.com/barryvdh/laravel-ide-helper, or if you just want to fix this specific instance you can add the following to your `tournament` model:

```php
/**
 * App\Models\Tournament
 *
 * @property App\Enums\TournamentType $type
 */
class Tournament extends Model 
{
    // Model definition...
}
```
