### ISSUE TITLE
Wrong return type of 'string' on Enum::toArray method

### ISSUE THREAD

**Issue by coatesap** [BenSampo/laravel-enum#195]
I might have missed something, but surely `\BenSampo\Enum\Enum::toArray()` should return `array` not `string`?

This seems important, as it's implementing the `Arrayable` interface which also expects it to return an array.

https://github.com/BenSampo/laravel-enum/blob/master/src/Enum.php#L515

**Comment by atymic** [comment]
This is our wonky way of getting around the problem of serialisation when "arraying" an eloquent model.
The interface doesn't actually have a type assigned. 
https://github.com/laravel/framework/blob/43bea00fd27c76c01fd009e46725a54885f4d2a5/src/Illuminate/Contracts/Support/Arrayable.php

If you have a better suggestion/way of doing it it would prob be a good idea to change.

**Comment by coatesap** [comment]
I see, so this is really to piggyback Laravel's special handling of attributes implementing `Arrayable` when calling `->toArray()` on a model instance? 
I suppose that's really a limitation in Laravel's code. What about if there was a `Stringable` contract, with special handling for that - then `Enum` could implement a `toString()` method?

**Comment by coatesap** [comment]
On reflection, I suppose what would be most beneficial, is a `toScalar()` method (defined in an appropriately-named interface), as then it would be useful for any classes that could be serialised to a float/int/string/etc. 

I came across the [JsonSerializable interface](https://www.php.net/manual/en/class.jsonserializable.php) which would cover occasions where the enum is json encoded, but obviously that doesn't apply when a model is being saved to the db, for instance.
