### ISSUE TITLE
Compatibility with php 5.6

### ISSUE THREAD

**Issue by Hizmarck** [BenSampo/laravel-enum#2]
Actualmente uso php 5.6.15, pienso que no es compatible con los valores de retorno de php 7, puesto que me genera errores en tiempo de ejecución:

http://php.net/manual/en/migration71.new-features.php

bueno, eso pienso, talvéz debería eliminarse la "compatibilidad" con php 5.6 

> "require": {
>         "illuminate/support": "~5.1",
>         "php" : "~5.6|~7.0"
>     },

**Comment by BenSampo** [comment]
Hola Hizmarck. Usted eres correcto, laravel-enum no es compatible con php 5.6. Lo he actualizado.
