### ISSUE TITLE
Strict comparison should be optional

### ISSUE THREAD

**Issue by uguurozkan** [BenSampo/laravel-enum#20]
The `strict` parameter of `in_array` function should be optional. There may be some cases where the only important thing is the value itself. Ex: `'1'`and `1`. I only want to check the value.

https://github.com/BenSampo/laravel-enum/blob/b9509bb845d0e67b9a70cb8b4aaeeca63a8587cf/src/Rules/EnumValue.php#L29

**Comment by BenSampo** [comment]
Thanks, have fixed this now.
