### ISSUE TITLE
Need a toArray() fn that returns enum descriptions

### ISSUE THREAD

**Issue by rsubr** [BenSampo/laravel-enum#21]
@BenSampo thanks a ton for this module and your blog post, using enums has greatly simplified my code.

I'm using enums to populate html `select` fields and `toArray()` almost satisfies my requirement. However, populating select field values with enum descriptions is more readable than using enum keys.

eg. Instead of `SADMIN, AUTHOR`, the select field would show `'Super Administrator', 'Blog Author'`.

I'm now repeating the same `toArrayDescription()` function in all of my Enum classes as shown below. Can we have a toArrayDescription() added to laravel-enum to address this use case?

```php
final class UserType extends Enum
{
    const SADMIN = 0;
    const AUTHOR = 1;


    /**
     * Get the description for an enum value
     *
     * @param $value
     * @return string
     */
    public static function getDescription($value): string
    {
        switch ($value) {
            case self::SADMIN:
                return 'Super admin';
            case self::AUTHOR:
                return 'Blog author';
        }
        return self::getKey($value);
    }

// returns ['Super Admin' => 0, 'Blog Author', => 1]
    public static function toArrayDescription()
    {
        $arr = [];

        foreach (self::getValues() as $v) {
            $arr[self::getDescription($v)] = $v;
        }
        return $arr;
    }
}
```

**Comment by BenSampo** [comment]
@rsubr Yes, this looks good to me. I'll add something like it in when I get a chance.

I was also thinking about making a better default for the getDescription method where it could guess a description for a key name e.g. `SuperAdministrator` would become `Super administrator`.

Glad you find the package useful 👍

**Comment by BenSampo** [comment]
@rsubr I've added a `toSelectArray` method. If you have any other methods that you often add to an enum, I've made the base Enum class macroable so you can extend it as you wish within your application.

https://github.com/BenSampo/laravel-enum#extending-the-enum-base-class

**Comment by rsubr** [comment]
@BenSampo works great! :pray:

Thanks for making it extensible.

You have even updated the project documentation! :astonished: :trophy:

**Comment by rsubr** [comment]
Further testing shows that `getDescription` method defined in my `UserType` child class does not get called by `toSelectArray`. It's calling the method defined in the `Enum` base class function instead.

In the `toSelectArray` method, can you please change `self::getDescription` to `static::getDescription` so the overridden `getDescription` from the child class will be called?

There's the code that needs to be changed:

```php
foreach ($array as $key => $value) {
//  $selectArray[$value] = self::getDescription($value);
    $selectArray[$value] = static::getDescription($value);
}
```

**Comment by BenSampo** [comment]
@rsubr  Yeah well spotted - have just pushed a fix for that.
