### ISSUE TITLE
How can I validate an Enum instance outside Controller?

### ISSUE THREAD

**Issue by bhaidar** [BenSampo/laravel-enum#211]
Hi,
I am trying to find out how to validate an Enum outside the Controller. 
Will this work fine?

````
if (new Enum(EmployeeStatus::class) !== $status) return;
````

Thanks

**Comment by BenSampo** [comment]
I don't know the context, but you could simply use `return EmployeeStatus::hasValue($status)`.

See https://github.com/BenSampo/laravel-enum#static-hasvaluemixed-value-bool-strict--true-bool
