### ISSUE TITLE
In PHP 8.1 enum became a reserved keyword

### ISSUE THREAD

**Issue by netpok** [BenSampo/laravel-enum#213]
So it cannot be used as a classname

https://wiki.php.net/rfc/enumerations#backward_incompatible_changes

**Comment by BenSampo** [comment]
This package will either be archived or completely rewritten when enums are in php core, so this is moot, at least for now.

**Comment by dambridge** [comment]
Just saw enums were approved for 8.1 now.

**Comment by nathan-io** [comment]
Hi @BenSampo 

> This package will either be archived or completely rewritten when enums are in php core, so this is moot, at least for now.

With PHP 8.1's GA release expected in November, I wanted to see if you'd given any more thought to this?

My two cents, I love the package and we're leveraging it extensively in several projects. I have fewer tables and safer code. So I'd personally love to see it refactored and maintained.  

Laravel will inevitably add native support for native PHP enum casting, validation, etc., though likely not to the degree offered by this package. 

And regardless, I'm sure there will be many PHP <8.1 Laravel applications (also constrained to earlier versions of Laravel and/or other dependencies) where this package would continue to be just as useful as it is even in greenfield PHP 8.0 projects today.

I hope to get your thoughts on the future of the package, and really appreciate your hard work!
