### ISSUE TITLE
Force locale on getLocalizedDescription

### ISSUE THREAD

**Issue by trippo** [BenSampo/laravel-enum#217]
Actually is impossible to have a localized description passing a custom locale.

**Comment by BenSampo** [comment]
Sorry, I'm not sure what you mean. Please can you explain in more detail?

**Comment by trippo** [comment]
If i have a localized enum like 
```php
final class PaymentType extends Enum implements LocalizedEnum
{
    const Paypal =   'P';
    const BankTransfer = 'B';
    const CreditCard = 'C';
    const ApplePay = 'A';
}
```
I  can't  print BankTransfer description forced to it locale without change app Locale

**Comment by BenSampo** [comment]
If you don't want it to be localized, don't implement the `LocalizedEnum` contract:

```php
final class PaymentType extends Enum
{
    const Paypal =   'P';
    const BankTransfer = 'B';
    const CreditCard = 'C';
    const ApplePay = 'A';
}
```

**Comment by trippo** [comment]
I want to localize, but i want in certain cases force the locale language.

**Comment by trippo** [comment]
Example: i want to send email to customer with the payment method localized with its locale, but to admin force it locale or call an external api with fixed it locale for invoicing

**Comment by BenSampo** [comment]
It's hard to advise without knowing the full context, but I guess you'll need to set the locale to your forced locale before reading e.g.:

```php
App::setLocale('en');
$paymentTypeDescription = PaymentType::getDescription(PaymentType::Paypal)
```

If you wanted to take this a step further, you could add a helper method to the enum:

```php
final class PaymentType extends Enum implements LocalizedEnum
{
    const Paypal =   'P';
    const BankTransfer = 'B';
    const CreditCard = 'C';
    const ApplePay = 'A';

    public static function getEnglishDescription($value): string
    {
        $previousLocale = App::currentLocale();
        App::setLocale('en');
        $englishDescription = static::getDescription($value);
        App::setLocale($previousLocale);
        
        return $englishDescription;
    }
}
```

Which you could then use like this:
```php
$paymentTypeDescription = PaymentType::getEnglishDescription(PaymentType::Paypal)
```

Hope that helps?

**Comment by trippo** [comment]
Yes i know this trick but is possible to define a getLocalizedDescription function with locale param like

```php 
PaymentType::getLocalizedDescription(PaymentType::BankTransfer,'en')
```

**Comment by BenSampo** [comment]
Without an update to the library, you can do this:

```php
final class PaymentType extends Enum implements LocalizedEnum
{
    const Paypal =   'P';
    const BankTransfer = 'B';
    const CreditCard = 'C';
    const ApplePay = 'A';

    public static function getTranslatedDescription($value, $locale): string
    {
        $previousLocale = App::currentLocale();
        App::setLocale($locale);
        $translatedDescription = static::getDescription($value);
        App::setLocale($previousLocale);

        return $translatedDescription;
    }
}
```

**Comment by BenSampo** [comment]
If you want to use this on multiple Enum classes, take a look at Macros:
https://github.com/BenSampo/laravel-enum#extending-the-enum-base-class
