### ISSUE TITLE
Constant and method naming does not respect PSR-2 / PSR-12

### ISSUE THREAD

**Issue by trippo** [BenSampo/laravel-enum#219]
Actually, the constants name on the stub are PascalCase, and the static methods respect the same name of the constants.
The [PSR-2](https://www.php-fig.org/psr/psr-2/) and [PSR-12](https://www.php-fig.org/psr/psr-12/) Style Guide standards say that: 
How are class constants named? 
upper = Uppercase with underscore separators.

So if the constants are uppercased, the static methods will be the same.
But the methods should be in camelCase.

So actually stub is this:
```
/**
 * @method static static OptionOne()
 * @method static static OptionTwo()
 * @method static static OptionThree()
 */
final class DummyClass extends Enum
{
    const OptionOne =   0;
    const OptionTwo =   1;
    const OptionThree = 2;
}
```

But it should be like this (also with constants with visibility declaration[PSR-12]):
```
/**
 * @method static DummyClass optionOne()
 * @method static DummyClass optionTwo()
 * @method static DummyClass optionThree()
 */
final class DummyClass extends Enum
{
    public const OPTION_ONE =   0;
    public const OPTION_TWO =   1;
    public const OPTION_THREE = 2;
}
```

If you agree I have a pull request ready to submit with retro compatibility.

**Comment by shaffe-fr** [comment]
Hi,
In the [accepted RFC](https://wiki.php.net/rfc/enumerations), enum cases use PascalCase and have no visibility.
Even if enums will only be live in PHP 8.1, I think it's a good idea that this package use this convention.

**Comment by BenSampo** [comment]
I'm with @shaffe-fr  on this one. This package is trying to emulate enums from other languages and we're already abusing class constants to achieve this, so it doesn't make sense to follow the PSR conventions intended for different purposes.

Although of course, there's nothing stopping anybody from following the above PSR standards with their own enums if they wish.
