### ISSUE TITLE
getDescription should return Uppercase of first letter of each word

### ISSUE THREAD

**Issue by michaelnguyen547** [BenSampo/laravel-enum#22]
at the moment, it only does uppercase of the first letter of the first word

```php
UserType::getDescription(UserType::SuperAdministrator); // Returns 'Super administrator'
```

I think it is proper to return 'Super Administrator' instead of 'Super administrator'

**Comment by BenSampo** [comment]
Hi @michaelnguyen547. Thanks for your feedback but I disagree on this point.

If you need that functionality for a particular enum, you can override the `getDescription` method on your enum class. If you need it for your whole project, you could create a new base enum class that overrides the `getDescription` method, which extends the enum class in this package, your enums would then extend from your base enum.

Hope that helps.
