### ISSUE TITLE
enum:annotate breaks enum for long constant name

### ISSUE THREAD

**Issue by wimski** [BenSampo/laravel-enum#225]
When the name of a constant is longer than `56`, the generated annotation gets wrapped, breaking the enum. 

```php
/**
 * @method static static
 * THIS_CONSTANT_NAME_IS_LONGER_THAN_56_CHARACTERS_AND_IS_WRAPPED()
 */
class MyEnum
{
    public const THIS_CONSTANT_NAME_IS_LONGER_THAN_56_CHARACTERS_AND_IS_WRAPPED = 'foo';
}
```

**Comment by BenSampo** [comment]
Thanks for logging this. I would accept a PR with tests to fix it.

**Comment by wimski** [comment]
> Thanks for logging this. I would accept a PR with tests to fix it.

Done #226
