### ISSUE TITLE
Disable wiki

### ISSUE THREAD

**Issue by spawnia** [BenSampo/laravel-enum#234]
Hi @BenSampo 👋 

Love your package to bits! I have been wondering what's in the wiki today, and noticed it is pretty much empty.

![image](https://user-images.githubusercontent.com/12158000/141857753-ecfe4f1b-f270-49d2-b0bd-a6195c038b41.png)

You can disable this feature in GitHub and save others a useless click.

**Comment by BenSampo** [comment]
Thanks @spawnia - the wiki is no more :)
