### ISSUE TITLE
Custom validation message for EnumValue

### ISSUE THREAD

**Issue by alexandruu** [BenSampo/laravel-enum#237]
Hy,

I have a Form Request with a custom validation rule:

`$rules = [
            'input.value' => ['required', new EnumValue(ValueEnum::class, false)],
];`

Validation works fine but the message received is ambiguous:

> The value you have entered is invalid.

Is there a way to change this message to include at least the attribute in it?

**Comment by BenSampo** [comment]
Hi @alexandruu, you can set a specific message using the `messages` method on your form request as per the Laravel docs: https://laravel.com/docs/8.x/validation#customizing-the-error-messages

e.g.

```php
public function messages()
{
    return [
        'input.value. enum_value' => 'Your custom validation message',
    ];
}
```

Or you can change it for your whole project by following the localization instructions:
https://github.com/BenSampo/laravel-enum#localization

**Comment by alexandruu** [comment]
Thanks for the reply, @BenSampo !

I've tried with method messages() and first I didn't know how to target the class EnumValue() from the conditions. After your reply I've tested  with **input.value.enum_value** but the received message hasn't changed: 

> The value you have entered is invalid.

Is there another way to target the class EnumValue() from the conditions?

**Comment by BenSampo** [comment]
It works if you use the pipe syntax:
https://github.com/BenSampo/laravel-enum#pipe-validation

But not if you use the class syntax - I'll have to look into that.

**Comment by alexandruu** [comment]
With pipe syntax it's working! Thank you very much, @BenSampo !

`$rules = [ 'input.value' => 'required|enum_value:' . ValueEnum::class];`

and method

```
public function messages()
{
    return [
        'input.value.enum_value' => 'Your custom validation message',
    ];
}
```
it's producing:

> Your custom validation message

**Comment by spawnia** [comment]
When used  as an object, `EnumValue` falls back to the same translation key as the pipe syntax based rule. It just requires that the language files were published.
