### ISSUE TITLE
Wrong return type for `FlaggedEnum::flags` method

### ISSUE THREAD

**Issue by eli-s-r** [BenSampo/laravel-enum#238]
The [`flags` method on `FlaggedEnum`](https://github.com/BenSampo/laravel-enum/blob/27e5a82e1830495e6b88bab6d38389b730c05e39/src/FlaggedEnum.php#L52) as documented as returning `void`, when it  returns an instance of itself (not sure if there's a reason `self` is used as the runtime return type instead of `static`). 

Happy to make a PR for this, though before doing so it'd be great to know of any reasoning behind using `self` instead of `static` here :)

**Comment by BenSampo** [comment]
Fixed in #241
