### ISSUE TITLE
`Enum::toArray()` does not return `array`

### ISSUE THREAD

**Issue by mikield** [BenSampo/laravel-enum#244]
Shouldn't this method https://github.com/BenSampo/laravel-enum/blob/30e3b3798807e4ed8d1e4da9f92d6cc1ac5a952a/src/Enum.php#L559-L567
transform Enum to array?

What i really am expecting is something:
```php
public function toArray() 
{ 
    return [$this->key => $this->value];
} 
```
Then `toArray` will really transform `Enum` instance to an array.

**Comment by spawnia** [comment]
#250 explains why the current implementation was chosen. I agree it is wrong though - the interface we are implementing clearly states that the method should return an `array`: https://github.com/laravel/framework/blob/2ff0764eda56d5653459153802b97c6007fd3d3d/src/Illuminate/Contracts/Support/Arrayable.php#L9-L17

Changing the methods return type now is a breaking change, but it might be one we have to make at some point anyways if Laravel ever adds a strong return type hint to their interface. With that, the conversion of `Enum` instances inside of `Collection` becomes somewhat more clunky - maybe we should remove the interface entirely in the next major version?

**Comment by mikield** [comment]
I just looked at how `toArray()` of the `Collection` class behaves, and I see now why `toArray` of `Enum` is returning a value.

But, as your test describes, we do not get the keys. 
Is not const names expected to be the keys?


Sorry for my English :)

**Comment by spawnia** [comment]
It might be more desirable for some to have the key instead of the value. Again, changing this behaviour would be a breaking change and require a major version bump. I think we should remove the implementation of `Arrayable` completely instead.
