### ISSUE TITLE
Installing with Laravel 9 blocked due to dependency on composer/composer

### ISSUE THREAD

**Issue by spawnia** [BenSampo/laravel-enum#249]
I cannot install this package with Laravel 9 because it depends on `composer/composer`. Its latest release does not support `symfony/console:^6`: https://github.com/composer/composer/blob/23b0a3819bb74214f04a0799c6f998c9822f54f4/composer.json#L35

Why do we have a dependency on `composer/composer` anyway, is it needed?

**Comment by BenSampo** [comment]
I replaced https://github.com/hanneskod/classtools with composer to handle iterating though classes when applying annotations (for the `php artisan enum:annotate` command).

See https://github.com/BenSampo/laravel-enum/commit/e36641cf52dec61e9838cd76934d822ca183d232

I've been able to successfully install on L9 so not sure where the issue is.

**Comment by spawnia** [comment]
I wonder why you cannot reproduce the issue. Laravel 9 depends on `symfony/console:^6`: https://github.com/laravel/framework/blob/dfef6a13059948543b1939a1437cfccb8ea1d3fb/composer.json#L33 - this should be enough to reproduce the conflict.

**Comment by marcoraddatz** [comment]
Can confirm it works. Make sure to upgrade to v5.1.

**Comment by davejamesmiller** [comment]
I ran into the same problem when using [Testbench](https://packages.tools/testbench/) for a package:

```
bensampo/laravel-enum[v5.0.0, ..., v5.1.0] require composer/composer ^2.2 -> satisfiable by composer/composer[2.2.0, ..., 2.2.6].
composer/composer[2.2.0, ..., 2.2.6] require symfony/console ^2.8.52 || ^3.4.35 || ^4.4 || ^5.0 -> satisfiable by symfony/console[v2.8.52, v3.4.35, ..., v3.4.47, v4.4.0, ..., v4.4.37, v5.0.0, ..., v5.4.3].
laravel/framework v9.0.0 requires symfony/console ^6.0 -> satisfiable by symfony/console[v6.0.0, v6.0.1, v6.0.2, v6.0.3].
You can only install one version of a package, so only one of these can be installed: symfony/console[v2.8.52, v3.3.0, ..., v3.4.47, v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3, v6.0.0, v6.0.1, v6.0.2, v6.0.3].
Conclusion: don't install laravel/framework v9.0.1 (conflict analysis result)
```

Yet it worked fine on an application. So I checked the installed versions on the application:

```
$ composer info
$ com info | grep -E 'bensampo/laravel-enum|composer/composer|laravel/framework|symfony/console'
bensampo/laravel-enum              v5.1.0
composer/composer                  dev-main 48758c0
laravel/framework                  v9.1.0
symfony/console                    v6.0.3
```

So it's using the development version of `composer/composer`. The difference is the application has [this](https://github.com/laravel/laravel/blob/345e46569d4b6a5c7093991a3257cdc0dcfe776b/composer.json#L60-L61) in `composer.json`:

```jsonc
{
    //...
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Adding the same thing to the package allowed it to be installed.

**Comment by spawnia** [comment]
Thanks @davejamesmiller, adding the following to `composer.json` did the trick for me.

```
{
    //...
    "minimum-stability": "dev",
    "prefer-stable": true
}
```
