### ISSUE TITLE
Enum error factories

### ISSUE THREAD

**Issue by fatihdurmaz** [BenSampo/laravel-enum#256]
I get an error when I initialize the enum value from 0.
 Warning: 1265 Data truncated for column 'lesson_type' at row 1 (SQL: insert into `lessons` (`lesson_name`, `lesson_type`, `updated_at`, `created_at`) values (Ad ea omnis quia numquam perferendis., -1, 2022-03-14 17:22:26, 2022-03-14 17:22:26))
my migration:
            $table->enum('lesson_type',LessonType::getValues())->default(LessonType::Kanun);
my enum:
final class LessonType extends Enum implements LocalizedEnum
{
    const Kanun =   1;
    const Yonetmelik =   2;
    const CumhurbaskaniKararnamesi = 3;
    const GenelKultur = 4;
    const UnvanDegisikligi = 5;
}
my factories:
        return [
            'lesson_name' => $this->faker->text(50),
            'lesson_type' => LessonType::getRandomInstance()
        ];

If I initialize the enum values ​​from 1, there is no problem.

**Comment by BenSampo** [comment]
The mysql error states that you're trying to set the `lesson_type` column to `-1`, which is an invalid enum value in your table ([I don't recommend the enum db column, I'd use an int here instead](https://github.com/BenSampo/laravel-enum#recommended)).

Are you [casting the attribute](https://github.com/BenSampo/laravel-enum#attribute-casting) on your model correctly?

**Comment by fatihdurmaz** [comment]
protected $casts = [
        'lesson_type' => LessonType::class,
    ];
my model cast
