### ISSUE TITLE
Validating empty string throws an error

### ISSUE THREAD

**Issue by samiheikki** [BenSampo/laravel-enum#266]
Validation file:
```
'event_type' => new EnumKey(EventType::class),
```

EventType.php
```
final class EventType extends Enum
{
    public const EVENT = 1;

    public const SEMINAR = 2;
}
```

Request:
```
{
  'event_type': '',
}
```

Expected result:
Validation returns error 422.

Actual result:
Validation returns error 500.

**Comment by spawnia** [comment]
Do you have a stacktrace?

**Comment by samiheikki** [comment]
> Do you have a stacktrace?

I do not.

**Comment by spawnia** [comment]
Closing due to lack of detailed information or reproducible test.
