### ISSUE TITLE
Error when running PHPstan on a Model using `QueriesFlaggedEnums` trait

### ISSUE THREAD

**Issue by pacoorozco** [BenSampo/laravel-enum#273]
I'm using the `QueriesFlaggedEnums` trait in the `Badge` model. I've defined a local scope which use the `hasAnyFlags()`. PHPstan raises an error like:

```
------ ---------------------------------------------------------------------------------- 
  Line   app/Models/Badge.php                                                              
 ------ ---------------------------------------------------------------------------------- 
  109    Call to an undefined method Illuminate\Database\Eloquent\Builder::hasAnyFlags().  
 ------ ---------------------------------------------------------------------------------- 
```

This is the Laravel code:
```
107:    public function scopeWithActuatorsIn(Builder $query, array $actuators): Builder
107:    {
109:        return $query
110:            ->where('active', true)
111:            ->hasAnyFlags('actuators', $actuators);
112:    }
```
[Someone was suggesting the use of PHP generics in order to avoid the problem](https://github.com/nunomaduro/larastan/issues/1307#issuecomment-1174454393). I've tried this approach using an [stub file](https://phpstan.org/user-guide/stub-files) but nothing has changed. 

The code could be find here: https://github.com/pacoorozco/gamify-laravel

Related to: nunomaduro/larastan#1307

**Comment by spawnia** [comment]
Have you tried adding generics to your own code? I think we should try and add them to this library too, but without having them in your code there is nothing to work with. This library cannot magically conjure up a connection from any `Builder` object to one where the generic `TModel` is provided.

**Comment by pacoorozco** [comment]
You have shared a very good point. I didn't think about it, let me try it. 🧑‍🏭
