### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by wimski** [BenSampo/laravel-enum#276]
Are there any plans to implement [generics](https://phpstan.org/blog/generics-in-php-using-phpdocs)? It's a pain to deal with `mixed` values. I would use `myclabs/php-enum` (which has [generics](https://github.com/myclabs/php-enum/blob/master/src/Enum.php)) instead if I didn't need those lovely Laravel integrations from this package.

**Comment by spawnia** [comment]
I could see adding that to the next major version. A pull request should probably follow https://github.com/BenSampo/laravel-enum/pull/269 to avoid duplicated efforts/merge conflicts.
