### ISSUE TITLE
Suggestions For Improvements (Discussion)

### ISSUE THREAD

**Issue by chrislentz** [BenSampo/laravel-enum#28]
I just heard about this package (via The Laravel Podcast) and I think it is awesome what you have done! I do have some suggestions / feedback though that I wanted to share.

I don't have time to put in a PR, so I thought I would just share my thoughts.

- I would love to see this more integrated with models, so you can utilize Laravel's mutators to save the values and get the descriptions with out having to use a separate class and static method.
- I also think it would be beneficial to define your enum values directly on the model instead of in a separate class. Maybe as an array:
```
protected $enums = [
    'type' => [
        0 => 'Administrator',
        1 => 'PaidMember',
        2 => 'Member'
    ],
    'status' => [
        0 => 'Approved',
        1 => 'Not Approved'
    ]
];
```
- You could also then use the model class as the main class you call so it could read more like this: 
```
$this->validate($request, [
    'type' => ['required', Rule::in(User::EnumOptions('type'))],
]);
```

Just my 2 cents. Keep up the awesome work!

**Comment by z-h-z-h** [comment]
@chrislentz This is what we all lack!

**Comment by BenSampo** [comment]
Hi Chris,

Thanks for your feedback.

To address your points:

1. You should be able to do this already with mutators. I'd rather not do this by default as it's not always appropriate.

2. I often create enums which are not coupled to a model or are applicable to multiple models. It's also more in keeping with other languages to define enums separately. You'd also lose the benefits of extending the base enum class.

Ben
