### ISSUE TITLE
QueriesFlaggedEnum::hasFlag broke on invalid argument signature

### ISSUE THREAD

**Issue by netpok** [BenSampo/laravel-enum#280]
QueriesFlaggedEnum got some typehints added, in the previous versions `Model::hasFlag('myenum', MyEnum::MyCase())` worked, but now it only accepts it like this: `Model::hasFlag('myenum', MyEnum::MyCase()->value)`.

Possible solution would be to allow `int|FlaggedEnum` as type.

**Comment by spawnia** [comment]
Open for pull requests.
