### ISSUE TITLE
comparison blocks saving

### ISSUE THREAD

**Issue by mihy** [BenSampo/laravel-enum#281]
Looks like comparison blocks saving.

I will add simplified example:

enum file:
```
<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

final class EnumStatus extends Enum
{
    public const NOT_STARTED = 10;
    public const STARTED = 20;
}
```

model file:

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Enums\EnumStatus;
use BenSampo\Enum\Traits\CastsEnums;

class MyEvent extends Model
{
    use CastsEnums;

    protected $casts = [
        'status' => EnumStatus::class,
    ];
}
```

controller file:
```
<?php

namespace App\Http\Controllers;

use Illuminate\Routing\Controller as BaseController;
use App\Models\MyEvent;
use App\Enums\EnumStatus;

class Controller extends BaseController
{
    public function testOne()
    {
        $event = MyEvent::find(1);

        $event->status = EnumStatus::NOT_STARTED;

        $event->status->is(EnumStatus::STARTED);

        $event->status = EnumStatus::STARTED;

        $event->save();

        return [
            'status' => $event->status,
        ];

    }
}
```

In result I will receive that status is 10 (NOT_STARTED)

If line

`$event->status->is(EnumStatus::STARTED);`

is removed, then i will receive that status is 20 (STARTED)

I also found a workaround. After comparison if I add:

`$event->refresh();`

then result will be as expected.

My env:
Docker PHP 8:0 (laravel sail)

**Comment by spawnia** [comment]
Please add a pull request with a failing test case.

**Comment by mihy** [comment]
Looks like in newest version there is no bug like that. Tests does not show that. Also tried with newest Laravel + Laravel-enums (6.x) and there as well there is no bug.

Bug is in the v4.2 with Laravel 8.x. 

So, you can close issue.
