### ISSUE TITLE
Enum method docblock: static vs self

### ISSUE THREAD

**Issue by wimski** [BenSampo/laravel-enum#284]
Wouldn't it be more accurate to write:
```php
@method static self METHOD_NAME()
```
...instead of:
```php
@method static static METHOD_NAME()
```

This would only need a change here:
https://github.com/BenSampo/laravel-enum/blob/76faf8cd638980883f0c0e1afdaa552ecef972a1/src/Commands/EnumAnnotateCommand.php#L57

**Comment by spawnia** [comment]
It is actually less accurate if you are using inheritance, see https://github.com/BenSampo/laravel-enum/pull/285.
