### ISSUE TITLE
Cast an array of enums

### ISSUE THREAD

**Issue by dimzeta** [BenSampo/laravel-enum#287]
Hello!

I see we can cast an enum like that:

```
    protected $casts = [
        'status' => StatusEnum::class,
    ];
```

But is is possible to cast an array of enums, like that for example?

```
    protected $casts = [
        'statuses' => StatusEnum::class . ':collection',
    ];
```

If there is another way to do the same thing, i'm interested!

**Comment by BenSampo** [comment]
Hello. If your model can have multiple statuses at the same time, this is a good use case for using a bitwise enum, see the docs:

https://github.com/BenSampo/laravel-enum#flaggedbitwise-enum
