### ISSUE TITLE
phpcs error with "enum" reserved keyword

### ISSUE THREAD

**Issue by bastos71** [BenSampo/laravel-enum#290]
Since a few days, phpcs trigger an error because of the use of the "enum" reserved keyword.

The commit that comes with this new sniffer is this one : https://github.com/PHPCompatibility/PHPCompatibility/commit/99bb9c2b87237ad53051f7b4a7fa14cb57961eb1

**Quickfix** : exclude the ruke `PHPCompatibility.Keywords.ForbiddenNames`

**Comment by spawnia** [comment]
That is a bug in phpcs. Using `Enum` as a class name is fine.

**Comment by bastos71** [comment]
@spawnia  Hum i'm not really sure, since this sniffer seems to trigger error if you use reserved words ( on the native level)

It's just like using `Trait` or `Function` as a class name in my opinion.

And even if it wasn't triggering any error, I think that because php 8.1 brings up the new `enum` feature, this package (wich is really great and useful, thank you for all your work 🙂) should use its own custom namings

**Comment by spawnia** [comment]
I disagree, this package is tested and works on PHP 8.1.

**Comment by bastos71** [comment]
It works I do not disagree 🙂
I'm just asking : do think it would be a good approach to call a class `Function` ? (for example)

```php
class Function {
  //...
}
``` 

If you think there is no problem then do not take my remark in consideration 😉

**Comment by spawnia** [comment]
Depends on the context. If I am implementing an AST of a programming language, I might have classes called `Variable`, `Function` or `Assignment`.
