### ISSUE TITLE
classDeclarationOffset unavailable when content removed with existing docblock

### ISSUE THREAD

**Issue by mikkoaf** [BenSampo/laravel-enum#293]
```
$ php artisan enum:annotate --folder=app
Wrote new phpDocBlock to /Foo/Etc/Enum.php

   TypeError 

  strpos(): Argument #1 ($haystack) must be of type string, null given

  at vendor/bensampo/laravel-enum/src/Commands/AbstractAnnotationCommand.php:138
    134▕             "\n" . $classDeclaration,
    135▕             $contents
    136▕         );
    137▕ 
  ➜ 138▕         $classDeclarationOffset = strpos($contents, $classDeclaration);
    139▕         // Make sure we don't replace too much
    140▕         $contents = substr_replace(
    141▕             $contents,
    142▕             sprintf("%s%s", $docBlock->generate(), $classDeclaration),

      +17 vendor frames
  18  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

``` 

For context, the enumerated class which causes this issue has currently 177 items in the docblock. Each string has a comment as follows

```
// This comment describes the foo bar enumerated constant
public const FOO_BAR_ENUMERATION = 'foo_bar_enumeration'
```

At a quick visual inspection I could not find any other cues besides these.

**Comment by mikkoaf** [comment]
Thanks!

I made the file long on purpose, it represents our real world enumeration list.

I manually also tested the new test case by shortening the list and found out that the class works but beyond `FOO_BAR_BAZ_ETC_LONG_NAME_FOR_TESTING_SAKE_113` the command starts failing. Should the test be shortened based on my findings?

**Comment by spawnia** [comment]
Thanks. You can leave the test as is - but perhaps there is something we can deduce from the point where it starts failing. Is the number of lines or the number of characters up until there somehow signifant (e.g. is it something like 1024)?

**Comment by mikkoaf** [comment]
The comment field is 8187 characters long up to the point when it becomes 8260 and it starts failing, being larger than 8192 (2^13)

**Comment by mikkoaf** [comment]
Using [preg_last_error()](https://www.php.net/manual/en/function.preg-last-error.php) I was able to confirm that the issue is code is `PREG_JIT_STACKLIMIT_ERROR`

**Comment by mikkoaf** [comment]
I updated the regex in the PR.
