### ISSUE TITLE
Support for string Enum Values

### ISSUE THREAD

**Issue by romanzipp** [BenSampo/laravel-enum#3]
A string support for Enums would be great with using the MySql "ENUM" datatype.

Currently the Validation rule is only checking for numeric values.

https://github.com/BenSampo/laravel-enum/blob/master/src/Rules/EnumValue.php#L29
```php
    public function passes($attribute, $value)
    {
        if (is_numeric($value) && in_array($value, $this->validValues)) { // <-
            return true;
        } else {
            return false;
        }
    }
```

**Comment by romanzipp** [comment]
I've submitted a pull request #4

**Comment by BenSampo** [comment]
Have merged your pull request and added some tests around using stings as enum values. Thanks for your contribution 👍
