### ISSUE TITLE
add extra attributes

### ISSUE THREAD

**Issue by e-rasekh** [BenSampo/laravel-enum#314]
Hi, I could't add extra attribute to enums.
I add an 'IsFinal' class, to attributes folder, such as 'description' class.
and add two method getAttributeDescription and getDescription, for isFinal. 
but below code returns null for "isFinal':
$descriptionAttributes = $constReflection->getAttributes(IsFinal::class);
        dd($descriptionAttributes);
while for description returns enum reflectionclass constant.
I really need to add some attributes to some enums.
is there any way ?

**Comment by spawnia** [comment]
I don't fully understand what you are asking, but it does not seem like a problem that can be solved in this library. It seems like you are just struggling with correct usage of PHP attributes and reflection, and this issue tracker is not a help forum.

**Comment by e-rasekh** [comment]
thanks, sorry, 
where can ask my question ?
