### ISSUE TITLE
Change getFriendlyKeyName visibility from private to protected

### ISSUE THREAD

**Issue by jenky** [BenSampo/laravel-enum#32]
Given these following constants

```php
const SUPER_ADMIN = 'super_admin';
const SUPER_MODERATOR = 'super_moderator';
const MODERATOR = 'moderator';
const PREMIUM_USER = 'premium_user';
```
`getDescription` will return
```
S u p e r a d m i n
S u p e r m o d e r a t o r
Moderator
P r e m i u m u s e r
```

Since I was using upper snake case convention `ctype_upper` will return `false`. Override the `getDescription` method get the job done but I don't like this approach because there are so much `if`. Instead override `getFriendlyKeyName` would be better, I can format the final result to anything I want. E.g. use title case so `Super admin` would become `Super Admin`. But `getFriendlyKeyName` is `private`, so it is impossible to override it atm.

**Comment by BenSampo** [comment]
@jenky Instead I've set up the getDescription method to cope with keys formatted in uppercase snake case, like in your example.

Update to 1.15.0 and you should be good!
