### ISSUE TITLE
Calling translator in boot breaks translation loading

### ISSUE THREAD

**Issue by netpok** [BenSampo/laravel-enum#321]
This package is is calling translation as part of the boot process. This triggers the loading of all currently registered translation which in turn prevents the loading of any other translations that were registered later.

**Comment by netpok** [comment]
Reproduce steps: https://github.com/laravel/framework/issues/47194

**Comment by spawnia** [comment]
This is related to, but not the same as https://github.com/BenSampo/laravel-enum/issues/245. Feel free to chime in at https://github.com/BenSampo/laravel-enum/issues/245#issuecomment-1538038415, I am not sure which one of the proposed merge requests I want to pursue further.

**Comment by spawnia** [comment]
Fixed with https://github.com/BenSampo/laravel-enum/releases/tag/v6.4.0.
