### ISSUE TITLE
validateEnumValue does not exist

### ISSUE THREAD

**Issue by Livijn** [BenSampo/laravel-enum#326]
When I updated to 6.4.0 my tests are throwing exceptions: 
> validateEnumValue does not exist

Pretty sure it's related to this: https://github.com/BenSampo/laravel-enum/pull/324

**Comment by spawnia** [comment]
Summoning @shaffe-fr, would you happen to have an idea how to fix this?

**Comment by shaffe-fr** [comment]
Hey @Livijn, can you show us the failing test?
Thanks

**Comment by shaffe-fr** [comment]
Do you register `EnumServiceProvider` manually?

**Comment by Livijn** [comment]
No, and I can see the `make:enum` command registered if I use `php artisan list`.

**Comment by Livijn** [comment]
It works! :)

**Comment by spawnia** [comment]
Fixed with v6.4.1.

**Comment by shaffe-fr** [comment]
Great, sorry for the hiccup!
