### ISSUE TITLE
Add `$hidden` property to Enums

### ISSUE THREAD

**Issue by TanisukeGoro** [BenSampo/laravel-enum#331]
Thank you for offering this convenient package.

## Problem
In long-term projects, Enums can accumulate values that are no longer used. Although these values can be deleted, sometimes they can't be because it may affect other systems. In particular, in Laravel-Enum, trying to create an instance with an undefined value causes an error.

## Proposed Solution
I propose to add a new $hidden property to Laravel-Enum classes to hide unwanted enum values. This property is inspired by the `$hidden` attribute in Laravel's Eloquent Model.

## Example Usage:
```php
<?php

declare(strict_types=1);

namespace App\Enums;

use BenSampo\Enum\Enum;
use BenSampo\Enum\Contracts\LocalizedEnum;

/**
 * @method static static Administrator()
 * @method static static Moderator()
 * @method static static Subscriber()
 * @method static static SuperAdministrator()
 *
 * @extends Enum<string>
 */
final class UserType extends Enum implements LocalizedEnum
{
    public const Administrator = 'administrator';
    public const Moderator = 'moderator';
    public const Subscriber = 'subscriber';
    public const SuperAdministrator = 'super_administrator';

    // add hidden property
    protected $hidden = [
        self::Moderator,
        self::Subscriber
    ];
}

```

```php
# before
UserType::asSelectArray()
array:4 [
    "administrator" => "administrator description",
    "moderator" => "moderator description",
    "subscriber" => "subscriber description",
    "super_administrator" => "super administrator description",
  ]
(※ ↑ assuming the description is defined in enums.php)

# after
UserType::asSelectArray();
array:4 [
    "administrator" => "administrator description",
    "super_administrator" => "super administrator description",
]

```

This will allow us to hide values that are no longer needed, making the Enums more manageable within the project. In the future, providing makeHidden and makeVisible methods would allow dynamic toggling of visibility.

## Preliminary Implementation
I have implemented a basic version of this feature in my fork of the repository, which can be found [here](https://github.com/TanisukeGoro/laravel-enum/pull/1). This implementation is not final, but it demonstrates how the `$hidden` property can be used.

I would like to discuss this feature and continue the implementation with feedback and guidance from the community.

**Comment by spawnia** [comment]
Closing, as I no longer plan to develop this library further - see https://github.com/BenSampo/laravel-enum/issues/332.
