### ISSUE TITLE
EnumServiceProvider breaks nova translations

### ISSUE THREAD

**Issue by cweiske** [BenSampo/laravel-enum#342]
When using this package, translations in Laravel Nova are broken. See #136 for an earlier issue.

This is the same issue as https://github.com/msurguy/Honeypot/issues/64 - see there for a truckload of other linked issues.

`BenSampo\Enum\EnumServiceProvider` is booted very early, and already uses the translator.
`Laravel\Nova\NovaServiceProvider` is booted later and adds additional configuration to the translator.
Unfortunately, the translator has already loaded its configuration because of `EnumServiceProvider`, and thus ignores the "new" configuration provided by Nova.

When `EnumServiceProvider` does not use the translator, everything is fine.

---

An attempt to fix this was tried in #145 and #141, and the latter was merged. This fix was reverted by #227, so the problem is back.

**Comment by spawnia** [comment]
Does https://github.com/BenSampo/laravel-enum/pull/324 not fix this for you? Are you using the latest version?

**Comment by cweiske** [comment]
We are using Laravel 8.83.27 and thus cannot use laravel-enum v6 - we are stuck with v4.

**Comment by spawnia** [comment]
This package will not be developed further, and I will not backport fixes to older versions, thus I am closing this issue.
