### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by YevheniiVolosiuk** [BenSampo/laravel-enum#347]
PHP: 8.1.2
Laravel Framework 10.42.0

![image](https://github.com/BenSampo/laravel-enum/assets/77569229/d4bb4ac9-b03e-4467-9d80-ffc23af787e3)

**Comment by spawnia** [comment]
Using this library is no longer recommended, especially for new projects. PHP 8.1 supports enums natively.

See https://github.com/BenSampo/laravel-enum/issues/332.
