### ISSUE TITLE
Library is not extendable

### ISSUE THREAD

**Issue by Ciaro** [BenSampo/laravel-enum#36]
Hi There.

Thank you for this library!

I wanted to extend your Enum Base class, but a lot of methods are private. Could you convert those to protected? 

Also, you probably want to replace those 'self' references to 'static' then, for the LSB.

Thanks in advance!

Best regards,

Ciaro

**Comment by BenSampo** [comment]
@Ciaro I'm pretty busy at the moment and likely wont get to this for a few weeks. If you submit a PR to make these changes, I'm happy to merge it in.

Thanks!
