### ISSUE TITLE
How do I dependency Inject in Livewire?

### ISSUE THREAD

**Issue by Umar-Khan-Yousafzai** [BenSampo/laravel-enum#360]
Hi, Ben Sampo,
First of all your project is extremely interesting and has helped me a lot. It works perfectly fine but now my company in doing a lot into coding structure and reducing the technical debt. 

Now the problem arise in Livewire, that in the boot() function, I am using Dependency Injection, but when I do it with Enum it gives me error:

Code:
![image](https://github.com/user-attachments/assets/58120c15-2283-4eb3-b5ad-60fb81bc9cab)

Error
![image](https://github.com/user-attachments/assets/deb3bb22-4313-4738-87d9-6f33a0d999da)

Can you please let me know how can I resolve this? I have checked your instantiation code but it doesn't tell what to do in case of dependency Injection????

**Comment by spawnia** [comment]
Using this library is no longer recommended, especially for new projects. PHP 8.1 supports enums natively.
 See https://github.com/BenSampo/laravel-enum/issues/332.

To reduce technical debt, I recommend you to [migrate to native PHP enums](https://github.com/BenSampo/laravel-enum#migrate-to-native-PHP-enums).
