### ISSUE TITLE
Country List

### ISSUE THREAD

**Issue by sirthxalot** [BenSampo/laravel-enum#37]
Hi folks!

First of all thank you @BenSampo for creating this package - it helps and works just fine.

If you are interested I have made a snippet for a country enumeration in english:
https://gist.github.com/sirthxalot/24507fb57964d1b7b660f08fdfebf9ce

Just thought may some other folks are interested in this. 

Maybe a independent documentation where we can share snippets would be cool. Are you interested? I usually use [VuePress](https://vuepress.vuejs.org/) in combination with GitHub pages. Just an idea.

best regards
Alexander Bösch

**Comment by BenSampo** [comment]
Hey @sirthxalot - Nice idea!

I've set up a md file as a list of common enums as a way to kick this off. I've linked to it from the readme.

[Enum library](https://github.com/BenSampo/laravel-enum/blob/master/enum-library.md)

**Comment by sirthxalot** [comment]
Great and thank you for your quick response.

**Comment by FrancoisDucobu** [comment]
Hello everyone,

Is it me or the list is reversed ?

I think it should be 

const Belgium = "BE";

Regards,

Francois

**Comment by FrancoisDucobu** [comment]
It's more logical to use

Countries::Belgium 

and get the BE value

**Comment by BenSampo** [comment]
@FrancoisDucobu Depends on the use case. Feel free to create a flipped version and I can include it in the library.

**Comment by FrancoisDucobu** [comment]
Ok i'll do it.
Thanks
