### ISSUE TITLE
hasKey() is case insensitive, but getValue() is case sensitive

### ISSUE THREAD

**Issue by musa11971** [BenSampo/laravel-enum#42]
```php
const Watching  = 0;
```

```php
UserLibraryStatus::hasKey('watching'); // true
UserLibraryStatus::hasKey('Watching'); // true
```
The above would make think that `getValue` would also accept both strings, but that's not true.

```php
UserLibraryStatus::getValue('watching');
```

throws the following exception:
```js
{
  "message": "Undefined index: watching",
  "exception": "ErrorException",
  "file": ".../project/vendor/bensampo/laravel-enum/src/Enum.php"
}
```

Is this intended? I would personally prefer it if the `getValue` function would also be case insensitive.

**Comment by BenSampo** [comment]
Hi @musa11971 , thanks for spotting the issue and submitting a PR.

I'm of the opinion that hasKey is wrong here and that it should be case sensitive, so it should be:

```php
UserLibraryStatus::hasKey('watching'); // false
UserLibraryStatus::hasKey('Watching'); // true
```

**Comment by musa11971** [comment]
Sure, that makes sense too @BenSampo - I've modified my PR.

`hasKey` and `getValue` are now both case sensitive.
