### ISSUE TITLE
Enum Instance Support

### ISSUE THREAD

**Issue by heywhy** [BenSampo/laravel-enum#46]
A pull request (https://github.com/BenSampo/laravel-enum/pull/45) was created by me to support enum instance instead of using the literal support which is error-prone, having the feature reduces bypassing of an enum constant value. One can easily typehint the enum on  methods, constructors and functions.

E.g.

```php

$userType = UserType::getInstance(UserType::Administrator);

// This way one is rest assured that the
// user's type is from the UserType enum.
createUser(array $data, UserType $userType)
{
    if ($userType->equals(UserType::Administrator)) {
        // ...;
    } else {
        // ...;
    }
}
```

**Comment by BenSampo** [comment]
Nice work @heywhy, I've merged your pull request in. I've made a few tweaks and added a few extra features too, you might want to have a quick look at the readme before use.

Thanks for the contribution 👍
