### ISSUE TITLE
Bug: Validation on integer value

### ISSUE THREAD

**Issue by samuelcorreadossantos** [BenSampo/laravel-enum#47]
@BenSampo , in `vendor/bensampo/laravel-enum/src/Enum.php` on method `hasValue`, the [pipe validation](https://github.com/BenSampo/laravel-enum#pipe-validation) fails if values of my enum class is integer.

Example:

```
<?php

namespace App\Enums;

use BenSampo\Enum\Contracts\LocalizedEnum;
use BenSampo\Enum\Enum;

final class EGenero extends Enum implements LocalizedEnum
{
    public const BAR = 1;
    public const FOO = 2;
}
```

This is due to the data conversion you make to string. I want to leave the suggestion not to convert the data to string because the Laravel 5.8 validation understands that 1 is deferential from "1"

`return in_array(>>>remove>>>(string)<<<remove<<< $value, array_map('strval', $validValues), true);`

**Comment by BenSampo** [comment]
Hi @samuelcorreadossantos, the hasValue method defaults to strict type checking where 1 !== "1". It's possible to specify loose type checking by passing a boolean as a second parameter like this:

``` php
'user_type' => 'required|enum_value:' . UserType::class . ',false',
```

Don't forget that unless specifically cast to an integer, values in your request data will be strings (e.g. values passed by a form).

**Comment by samuelcorreadossantos** [comment]
It worked. Thanks very much @BenSampo
