### ISSUE TITLE
Cannot use @INJECT in blades to access ENUMs

### ISSUE THREAD

**Issue by ShadowCyclist** [BenSampo/laravel-enum#49]
Hey Ben,
I've been using your package in a recent project and noticed when deploying to PROD, that using "composer install --no-dev" causes an error with you package. I wondering if that's due to the positioning of "laravel/framework": "5.8.*" under "require-dev"? I've removed the --no-dev in my docker build script, but it'd be nice to remove dev components for PROD environments.

**Comment by ShadowCyclist** [comment]
Please ignore this. I found the issue.
I was using Enums in a blade via @INJECT. This used to work, but something changed?
Anyway, its was a good prompt to move code & logic back into my controllers. ;)

**Comment by BenSampo** [comment]
Glad you sorted it :)
