### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by xmas** [BenSampo/laravel-enum#5]
the docs for "getValue" have sample code that is "getKey"

getValue(string $key): int
Returns the value for the given enum key.

UserType::getKey('Moderator'); // Returns 1

**Comment by BenSampo** [comment]
Well spotted, thanks. Have fixed.

https://github.com/BenSampo/laravel-enum/commit/aa607c327929c2899c8e12b1996d3d7f7b115738
