### ISSUE TITLE
Can not use the new `Attribute casting` feature

### ISSUE THREAD

**Issue by bolechen** [BenSampo/laravel-enum#51]
The result when i test use tinker is always null.
Where am i wrong? Thanks for the good package.

<img width="603" alt="Screen Shot 2019-05-04 at 23 15 39" src="https://user-images.githubusercontent.com/195015/57181148-c76c8700-6ec2-11e9-91cd-e9e4458ff92f.png">

<img width="1210" alt="Screen Shot 2019-05-04 at 23 15 29" src="https://user-images.githubusercontent.com/195015/57181162-de12de00-6ec2-11e9-9c2f-50c7d7021cdd.png">

**Comment by BenSampo** [comment]
Hi @bolechen - the key name in the `$enumCasts` array should be the name of the column in the db table. So looking at your examples I think you need:

```php
protected $enumCasts = [
    'role' => UserRole::class,
];
```

**Comment by bolechen** [comment]
> Hi @bolechen - the key name in the `$enumCasts` array should be the name of the column in the db table. So looking at your examples I think you need:
> 
> ```
> protected $enumCasts = [
>     'role' => UserRole::class,
> ];
> ```

it works. thx for quick response.
