### ISSUE TITLE
Validation is not working

### ISSUE THREAD

**Issue by zefexdeveloper** [BenSampo/laravel-enum#60]
I'm trying EVERYTHING to make the validation work but it doesn't.

```php
final class PlanInterval extends Enum
{
    const Day = 0;
    const Month = 1;
    const Year = 2;
}
```

Form Request:
```php
public function rules()
{
    return [
        'price' => ['required', 'numeric'],
        'period' => ['required', 'numeric', 'min:1'],
        'interval' => ['required', new EnumValue(PlanInterval::class)],
    ];
}
```

```php
<div class="form-group row">
    <label for="interval" class="col-md-4 col-form-label text-md-right">{{ __('Interval') }}</label>

    <div class="col-md-6">
        <select class="custom-select" id="interval" name="interval">
            @foreach($intervals as $key => $value)
                <option value="{{ $value }}" @if($plan->interval->is($key)) selected @endif>{{ $value }}</option>
            @endforeach
        </select>
    </div>
</div>
```

PlanController:

```php
/**
 * Show the form for editing the specified resource.
 *
 * @param  int  $id
 * @return Response
 */
public function edit($id)
{
    $plan = Plan::find($id);
    $intervals = PlanInterval::toSelectArray();

    return view('panel.plans.edit', compact('plan', 'intervals'));
}
```

It always say that it's the wrong value in the validation. What is happening? I'm using Laravel 5.8.

**Comment by BenSampo** [comment]
The values passed to your controller from the form will be strings. Specifically, if you pick the plan "Year" in the select, the value passed to the controller is "2" and not 2, which is what you're trying to validate.

There are couple of solutions to this, but the most elegant and expressive way I've found is to cast the request param to an int before validating. You can do that in the form request itself as explained in a blog post I wrote here:

https://sampo.co.uk/blog/manipulating-request-data-before-performing-validation-in-laravel

Essentially you should be able to do this in your form request class:

```php
/**
* Prepare the data for validation.
*
* @return void
*/
protected function prepareForValidation()
{
    $this->merge([
        'interval' => (int) $this-> interval,
    ]);
}
```

Another option is to turn of strict type checking on the `EnumValue` validation rule. You can do that like this:

```php
'interval' => ['required', new EnumValue(PlanInterval::class, false)],
```

I hope all of that helps. Give me a shout if it's still not working.

**Comment by zefexdeveloper** [comment]
@BenSampo I'm kinda confused with something here. You are preparing for validation the `interval` as `integer` it means that I would need to change the `option` `value` to `$key` instead of `$value`, something like this:

```
@foreach($intervals as $key => $value)
    <option value="{{ $key }}" @if($plan->interval->is($key)) selected @endif>{{ $value }}</option>
@endforeach
```

Because `PlanInterval::toSelectArray()` will return an array like `[0 => 'Day', 1 => 'Month', 2 => 'Year']`.

But what I don't understand is: why to use `EnumValue` instead of `EnumKey` as we are working with the key and not the value?

Regarding the solution: it worked only using the `prepareForValidation`, it doesn't seem to work using only by setting the strict mode to `false`.

**Comment by BenSampo** [comment]
@zefexdeveloper I think you're getting confused here between the key of the enum and the key of the array in your view.

`"Day"` is the enum key
`0` is the enum value

When you use `toSelectArray` you get a representation of the enum as an array keyed by the enum value - often HTML builders for selects will accept this format as an input, hence its inclusion in the package.

It sounds like you'll be better off using [`toArray`](https://github.com/BenSampo/laravel-enum#static-toarray-array) method instead which will give you a representation of the enum as an array keyed by the enum key. e.g.

```php
[
    "Day" => 0,
    "Month" => 1,
    "Year" => 2,
]
```

**Comment by zefexdeveloper** [comment]
Thank you very much @BenSampo, it's working like a charm. Keep up the good work.

**Comment by BenSampo** [comment]
Glad you got it sorted @zefexdeveloper 👍
