### ISSUE TITLE
is there any way to use with Laravel 5.3?

### ISSUE THREAD

**Issue by guzprada** [BenSampo/laravel-enum#63]
I have a huge project in L5.3, i expect to migrate in the next months but i want to know if i can use your package here.

What kind of dependencies are required from L5.4 not present in L5.3?

Thanks in advance.

**Comment by BenSampo** [comment]
Hi @guzprada I haven't tried running the package in L5.3 but I wouldn't be surprised if it worked without any modification. I'd be curious to know how you get on. If you do run into issues, let me know and we might be able to sort it out.
