### ISSUE TITLE
Casting Enum to string

### ISSUE THREAD

**Issue by atymic** [BenSampo/laravel-enum#65]
I've switched from the `myclabs/php-enum` package, and one of the things i've missed in the ability to cast an instance to string to get the value.

I was wondering if you would consider adding it to this library, so when you cast a Enum instance to a string you get the value (as a string).

For example:
```php
final class MyEnum extends Enum
{
    const TEST = 'test';
    const TEST_INT = 1;
}

(string) MyEnum::TEST(); // = 'test' 
(string) MyEnum::TEST_INT(); // = '1'

```

This is useful in views as well, as you can do `{{ $model->enum_casted_attr }}`.

Happy to create a PR + tests/etc as well 😄 

See:
https://github.com/myclabs/php-enum#documentation

**Comment by BenSampo** [comment]
Hi @atymic - this sounds like a sensible suggestion to me. Please take a look at using the magic [`__toString`](https://www.php.net/manual/en/language.oop5.magic.php#object.tostring) method, I think that will cover your use case.

Please include tests and updates to the readme with your PR.

Thanks in advance!

**Comment by atymic** [comment]
Yep, i'll create a PR tomorrow :)
Thanks

**Comment by poseso** [comment]
is this going to be merged ?
