### ISSUE TITLE
Add annotations to models 

### ISSUE THREAD

**Issue by atymic** [BenSampo/laravel-enum#69]
The enum casting on models is awesome, but it's a bit hard to remember that cast attributes are instances of the enum, rather than a string/int/etc.

Since there's already a command to annotate the enum, maybe we can add another to annotate the model like so?

```php
/**
 * App\Models\User
 *
 * @property \App\Enums\UserTypeEnum|null $user_type
 * @property \App\Enums\RoleEnum|null $role
 */
```

Will PR w/ tests if you are keen :)
Thanks!

**Comment by BenSampo** [comment]
Thanks for your work on the other features, you've done a great job, thanks!

More than happy to accept a PR for this feature too, if you would still like to develop it.

Cheers!
Ben
