### ISSUE TITLE
Trait method getAttributeValue collision

### ISSUE THREAD

**Issue by CreativeBulma** [BenSampo/laravel-enum#70]
Hi,

I'm trying to use this package within a model which already has an implementation of the getAttributeValue function and I then get an error due to the duplicity of this method definition (one in my model and one in the laravel-enum package).

```
PHP Fatal error:  Trait method getAttributeValue has not been applied, because there are collisions with other trait methods
```

How can I use this package in that context ?

**Comment by atymic** [comment]
Unfortunately this is a PHP limitation, so we can't fix it in this package.

The only way to use both packages would be to create a custom `getAttributeValue` on your model, and include the logic from both traits.

**Comment by CreativeBulma** [comment]
Thanks for your answer

**Comment by vadimwe** [comment]
> Unfortunately this is a PHP limitation, so we can't fix it in this package.
> 
> The only way to use both packages would be to create a custom `getAttributeValue` on your model, and include the logic from both traits.

How to fix this issue? Package conflicts with Laravel Translatable package...

**Comment by atymic** [comment]
As per my answer above:

> The only way to use both packages would be to create a custom getAttributeValue on your model, and include the logic from both traits.
