### ISSUE TITLE
Enum instance descriptions not switching locale

### ISSUE THREAD

**Issue by zarunet** [BenSampo/laravel-enum#72]
When switching locales on the fly, already created enum instances seems to ignore the locale change.

Here's an example of what i mean:

```php
// the app locale is currently 'en'
$na = \App\Enums\Continent::NorthAmerica();
echo $na->description; // echoes "North America"

App::setLocale('fr');
echo $na->description; // still echoes "North America" - unexpected

$na = \App\Enums\Continent::NorthAmerica() // re-instantiating
echo $na->description; // echoes "Amérique du Nord" as i expected
```

**Comment by atymic** [comment]
I'll have a look into this :)

**Comment by atymic** [comment]
This is because the description cached when creating the instance
https://github.com/BenSampo/laravel-enum/blob/master/src/Enum.php#L53-L62

I personally think this makes sense, as accessing the description multiple times does not incur the overhead of translating each time.

For your use case, use the following code:

```php
$na = \App\Enums\Continent::NorthAmerica();

echo \App\Enums\Continent::getDescription($na); // echoes "North America"

App::setLocale('fr');
echo \App\Enums\Continent::getDescription($na); // echoes "Amérique du Nord" as expected

```

**Comment by zarunet** [comment]
Thanks @atymic for your feedback, it indeed totally makes sense!  
After digging around, i discovered that an enum instance inside another object *does* switch locales (maybe it's creating a new instance each time under the hood?)

```php
// current locale is 'en'
$c = new \App\Models\Country();
$c->continent = \App\Enums\Continent::NorthAmerica();
echo $c->continent->description // echoes "North America"

App::setLocale('fr');
echo $c->continent->description; // echoes "Amérique du Nord"
```

Well, this is exactly what i wanted to do in the first place, so i guess the problem's solved, then? 😄

**Comment by atymic** [comment]
Ahh, looks like it creates a new instance when grabbing it from the model (using the magic getter)
https://github.com/BenSampo/laravel-enum/blob/master/src/Traits/CastsEnums.php#L23

Glad it was solved :)
