### ISSUE TITLE
Issue storing integer

### ISSUE THREAD

**Issue by DanielGilB** [BenSampo/laravel-enum#73]
Hi!

I have my Order model like this:

`	protected $enumCasts = [
		'status' => OrderStatusTest::class,
	];
`

I use toSelectArray() function in my controller to return array to my view

`$statuses = OrderStatusTest::toSelectArray();`

My select: 

`
            <select name="status" >
                @foreach ($statuses as $value => $status)
                <option value="{{ $value }}" >{{ $status }}</option>
                @endforeach
            </select>
`

Im trying to store like this

`$order->status = $request->status;`

But i get this error: `Value 7 doesn't exist in [0, 1, 2, 3, 4, 5, 6, 7]`

To solve I have to force cast to int like this:
`$order->status = (int) $request->status;`

What is the correct way to do it? 

Thanks you bro!

**Comment by BenSampo** [comment]
Hi @DanielGilB. Any property from a request is always a string so you'll need to cast it to an int at some point.  Either keep it as you have already or if you're making use of form request classes you might be interested in this blog post I wrote which allows you to manipulate request properties before validating them.

https://sampo.co.uk/blog/manipulating-request-data-before-performing-validation-in-laravel

Hope this helps.
