### ISSUE TITLE
Setting using casting

### ISSUE THREAD

**Issue by leeovery** [BenSampo/laravel-enum#77]
Hey,

Loving the new updates and just trying to refactor to use enum casting but having an issue. Not sure if it's a feature or bug but thought I'd ask anyway.

So I thought to set the user status using the static method as follows:

```
User::create([..., 'status' => UserStatus::Approved()]);
```

This works fine when setting as it casts down to the value as an int. But when fetching back out of DB, the int is pulled as a string and when attempting to cast back to a UserStatus enum it fails on the strict checking and I get the following exception msg: 

```
BenSampo\Enum\Exceptions\InvalidEnumMemberException : Value 0 doesn't exist in [0, 1]
```

So I thought to set the original cast as well which I was using before your enum casting. So the status attribute would cast to an int before being cast to the UserStatus enum.

This seems to work when fetching, but then fails when setting. When setting via a new user create method call, as shown above, I get the following error:

```
ErrorException : Object of class App\Enums\UserStatus could not be converted to int
```

It seems we need to check when setting if it's already an enum object or not and act accordingly.

I'm surprised this hasn't come up before though, so it's possible I'm missing something. I could work around it by using `UserStatus::Approved` as the value rather than an instance - perhaps that's the intended way...?

More than happy to provide a PR and tests if needed but thought I'd open the discussion first.

Thanks!
Lee

**Comment by BenSampo** [comment]
Hey @leeovery - thanks for logging this. I've just updated one of my projects with the same setup as your scenario to the latest version of laravel-enum and replicated the problem.

I did some investigation and have pushed a fix (3ad26ce). Make sure to update to v1.21.3 and you should be good to go.

Give me a shout if you're still having problems.

**Comment by xorock** [comment]
@BenSampo 

I'm having the same problem on 1.23:  `BenSampo\Enum\Exceptions\InvalidEnumMemberException
Value 1 doesn't exist in [1, 2]`

View:
`{{ Form::select('transaction_type', $transactionType, null, ['class' => 'form-control']) }}`

Controller:
`'transactionType' => TransactionType::toSelectArray(),` //TransactionType is localized if it makes difference

`Transaction::create($request->all())`

Transaction model:
```php
use CastsEnums;
protected $enumCasts = [
        'transaction_type' => TransactionType::class,
    ];
```

**Comment by BenSampo** [comment]
`$request->all()` will return an array like:

```php
[
  'transaction_type` => '1';
]
```

Note that the value of `transaction_type` is a string `'1'` and not an integer `1`. All request parameters are always interpreted as strings so you'll need to cast it to an int first. You're essentially trying to construct the enum with the value `'1'` instead of `1`, which is why it's throwing an error.

I've found the best way to manipulate request data is to use form request classes. Take a look at some examples of this here:
https://sampo.co.uk/blog/manipulating-request-data-before-performing-validation-in-laravel

Hope that helps.

**Comment by BenSampo** [comment]
@xorock Alternatively, on your model, you can cast to an int first, before casing to an enum like this:

```php
use CastsEnums;

protected $casts = [
  'transaction_type' => 'int',
];

protected $enumCasts = [
  'transaction_type' => TransactionType::class,
];
```

**Comment by drbyte** [comment]
> All request parameters are always interpreted as strings

👍 This has tripped me up more times than I care to admit  😊 


> on your model, you can cast to an int first, before casting to an enum

Is this worth adding as a tip to the docs?

**Comment by lcjury** [comment]
Hey @BenSampo 

why
```php
protected $enumCasts = [
  'transaction_type' => TransactionType::class,
];
```

doesn't implicitly adds the casts to integer on that column?

**Comment by BenSampo** [comment]
@lcjury Because the enum value could be a string

**Comment by lcjury** [comment]
Oh, I see, thanks for the fast answer!
