### ISSUE TITLE
Can not store the key on db:seed

### ISSUE THREAD

**Issue by omarname** [BenSampo/laravel-enum#78]
I'm using the attribute casting on my model.
On my UserTableSeed i tried to store the key of Countries Enum instead of the value like this:

`country => Countries::getInstance(Countries::MA)->key;`

But it throws an exception `BenSampo\Enum\Exceptions\InvalidEnumMemberException  : Value MA doesn't exist in`

But if i store the value of Enum it works.

Any suggestions to correct this.

By the way thanks for your work.

**Comment by atymic** [comment]
Can you post your enum class?

**Comment by BenSampo** [comment]
Hi @omarname - the intended use for attribute casting is that the enum value is resolved from the DB, not the key. 

I don't think resolving by key is something I'd like to build into the package, but if you'd like to override this for your particular use case, take a look at the `CastsEnums` trait. You should be able to override these methods directly in your model.

**Comment by omarname** [comment]
@atymic 

I use this library [Countries](https://gist.github.com/sirthxalot/24507fb57964d1b7b660f08fdfebf9ce) - submitted by [Alexander Bösch](https://github.com/sirthxalot)

**Comment by omarname** [comment]
@BenSampo It's usefull when the value of the enum is a string and the the key is an abbreviation, so we could possibly edit the value in the futur without breaking the app and keep the same key.

I'll try your solution, thanks a lot by the way.

**Comment by ahmedsaber111** [comment]
Hi @omarname,
Do you got a solution for your case? if yes, could you please share it.

**Comment by omarname** [comment]
Yes i used the same key/value abbreviation. Intead doing this `const AF = "Afghanistan";` i did this in the enum class `const AF = "AF";` 

So to get the the name of the country. you just add this method in your enum class:

```
public static function getDescription($value): string
{
    switch ($value) {
        case self::AF:
        return 'Afghanistan';
       // add the others country
    }

    return parent::getDescription($value);
}
```

**Comment by omarname** [comment]
```
final class Countries extends Enum
{
    const AF = "AF";
    //.......

   public static function getDescription($value): string
{
    switch ($value) {
        case self::AF:
        return 'Afghanistan';
       // .....
    }

    return parent::getDescription($value);
}
}
```
