### ISSUE TITLE
Checking if instance has value in array

### ISSUE THREAD

**Issue by atymic** [BenSampo/laravel-enum#79]
I'm really been enjoying working with this package, particularly the model integration.

I often do something similar to this:

```php
$booking->status->is(Status::DRAFT) || $booking->status->is(Status::PENDING) || $booking->status->is(Status::REVIEW) 
```

It gets a little verbose, particularly when checking many values.

I was wondering what your thoughts would be on adding an `in` function to the instance, for example:

```php
$booking->status->in([Status::DRAFT, Status::PENDING, Status::REVIEW])
```

It could also support the passing the choices as function arguments:
```
$booking->status->in(Status::DRAFT, Status::PENDING)
```

Let me know 😄

**Comment by BenSampo** [comment]
Agreed, looks great. PR away 👍

**Comment by atymic** [comment]
PR open in #80 	😄
