### ISSUE TITLE
As the test for hasValue in the Enum constructor is strict, it fails with form request data

### ISSUE THREAD

**Issue by kurucu** [BenSampo/laravel-enum#92]
I have used ::toSelectArray() to generate the select, then the EnumValue rule in the Request validator (having to switch strict to false, as the value is a string rather than integer).
As a result, trying to set the model value (which has been enumCast) fails, as it uses a strict test in the Enum constructor.
I don't think I've missed a better method? The casting is supposed to be done by enumCast, so casting beforehand to avoid the constructor failing seems pointless. Does the constructor need to avoid using strict comparisons?

**Comment by BenSampo** [comment]
Hi @kurucu ,

See https://github.com/BenSampo/laravel-enum/issues/77#issuecomment-521655856 and https://github.com/BenSampo/laravel-enum/issues/77#issuecomment-521657258 - I think these will help you.

Let me know if not.

Ben

**Comment by kurucu** [comment]
Implemented and fixed - thank you!

**Comment by kurucu** [comment]
I'll update the docs to point at this once I've learnt to run a pull request :)

**Comment by BenSampo** [comment]
Agreed, it should be in the docs. Rather than linking to the issue, I would prefer to explicitly state that if using integers as enum values and using `$enumCasts` that you also need to use `$casts` to avoid running into problems when taking data from forms.
