### ISSUE TITLE
Installing `bensampo/laravel-enum` into Laravel 6 removes `laravel/ui`

### ISSUE THREAD

**Issue by vaughany** [BenSampo/laravel-enum#99]
Not 100% sure if this belongs here, but reporting it here as it was installing this package that caused the issue.

Re-installing `laravel/ui` afterwards doesn't remove anything.

```
$ composer require bensampo/laravel-enum
Using version ^1.26 for bensampo/laravel-enum
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 1 removal
  - Removing laravel/ui (v1.0.0)
  - Installing zendframework/zend-eventmanager (3.2.1): Downloading (100%)         
  - Installing zendframework/zend-code (3.3.2): Loading from cache
  - Installing hanneskod/classtools (1.2.0): Downloading (100%)         
  - Installing bensampo/laravel-enum (v1.26): Loading from cache
...snip...
Package manifest generated successfully.
```

**Comment by drbyte** [comment]
@vaughany did you by any chance manually edit your `composer.json` to delete the `laravel/ui` entry before calling `composer require`? That would make Composer do the "remove" as in your example.

**Comment by BenSampo** [comment]
Are you able to reproduce this?

**Comment by vaughany** [comment]
@drbyte @BenSampo  ...I'm not able to reproduce this.  Weird.  I tend to never edit composer.json manually, but as I was diffing between this one in a fresh L6 install and one in a L5.8 project, I guess I must have?  I can't explain it otherwise.  I've just spun up a new L6 project and everything just works as expected...

Thinking about it further, I may have run `git clean -df`, accidentlally removing the composer.json file's addition of `laravel/ui`.

Sorry for the noise.

**Comment by BenSampo** [comment]
No worries @vaughany, glad you got it sorted in the end :)
